ALTER TABLE model_metadata 
  ADD COLUMN cached_token_cost NUMERIC(12,6) NOT NULL DEFAULT 0;

ALTER TABLE chat_messages 
  ADD COLUMN cached_token_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN cost NUMERIC(12,6) NOT NULL DEFAULT 0;

ALTER TABLE chat_list 
  ADD COLUMN cost NUMERIC(12,6) NOT NULL DEFAULT 0,
  ADD COLUMN input_token_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN output_token_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN cached_token_count BIGINT NOT NULL DEFAULT 0;