// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: inferenceservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Model struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url             string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Provider        string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	InputTokenCost  float64                `protobuf:"fixed64,5,opt,name=input_token_cost,json=inputTokenCost,proto3" json:"input_token_cost,omitempty"`
	OutputTokenCost float64                `protobuf:"fixed64,6,opt,name=output_token_cost,json=outputTokenCost,proto3" json:"output_token_cost,omitempty"`
	Progress        string                 `protobuf:"bytes,7,opt,name=progress,proto3" json:"progress,omitempty"`
	IsDownloaded    bool                   `protobuf:"varint,8,opt,name=is_downloaded,json=isDownloaded,proto3" json:"is_downloaded,omitempty"`
	IsDownloadable  bool                   `protobuf:"varint,9,opt,name=is_downloadable,json=isDownloadable,proto3" json:"is_downloadable,omitempty"`
	Status          int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_inferenceservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Model) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Model) GetInputTokenCost() float64 {
	if x != nil {
		return x.InputTokenCost
	}
	return 0
}

func (x *Model) GetOutputTokenCost() float64 {
	if x != nil {
		return x.OutputTokenCost
	}
	return 0
}

func (x *Model) GetProgress() string {
	if x != nil {
		return x.Progress
	}
	return ""
}

func (x *Model) GetIsDownloaded() bool {
	if x != nil {
		return x.IsDownloaded
	}
	return false
}

func (x *Model) GetIsDownloadable() bool {
	if x != nil {
		return x.IsDownloadable
	}
	return false
}

func (x *Model) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DownloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadModelRequest) Reset() {
	*x = DownloadModelRequest{}
	mi := &file_inferenceservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadModelRequest) ProtoMessage() {}

func (x *DownloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadModelRequest.ProtoReflect.Descriptor instead.
func (*DownloadModelRequest) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadModelRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type DownloadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadModelResponse) Reset() {
	*x = DownloadModelResponse{}
	mi := &file_inferenceservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadModelResponse) ProtoMessage() {}

func (x *DownloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadModelResponse.ProtoReflect.Descriptor instead.
func (*DownloadModelResponse) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListLLMModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLLMModelsRequest) Reset() {
	*x = ListLLMModelsRequest{}
	mi := &file_inferenceservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLLMModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLLMModelsRequest) ProtoMessage() {}

func (x *ListLLMModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLLMModelsRequest.ProtoReflect.Descriptor instead.
func (*ListLLMModelsRequest) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{3}
}

type ListLLMModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLLMModelsResponse) Reset() {
	*x = ListLLMModelsResponse{}
	mi := &file_inferenceservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLLMModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLLMModelsResponse) ProtoMessage() {}

func (x *ListLLMModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLLMModelsResponse.ProtoReflect.Descriptor instead.
func (*ListLLMModelsResponse) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{4}
}

func (x *ListLLMModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_inferenceservice_proto protoreflect.FileDescriptor

const file_inferenceservice_proto_rawDesc = "" +
	"\n" +
	"\x16inferenceservice.proto\x12\n" +
	"sortedchat\"\xb1\x02\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12(\n" +
	"\x10input_token_cost\x18\x05 \x01(\x01R\x0einputTokenCost\x12*\n" +
	"\x11output_token_cost\x18\x06 \x01(\x01R\x0foutputTokenCost\x12\x1a\n" +
	"\bprogress\x18\a \x01(\tR\bprogress\x12#\n" +
	"\ris_downloaded\x18\b \x01(\bR\fisDownloaded\x12'\n" +
	"\x0fis_downloadable\x18\t \x01(\bR\x0eisDownloadable\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\"5\n" +
	"\x14DownloadModelRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\"1\n" +
	"\x15DownloadModelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x16\n" +
	"\x14ListLLMModelsRequest\"B\n" +
	"\x15ListLLMModelsResponse\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.sortedchat.ModelR\x06models2\xc0\x01\n" +
	"\x10InferenceService\x12T\n" +
	"\rDownloadModel\x12 .sortedchat.DownloadModelRequest\x1a!.sortedchat.DownloadModelResponse\x12V\n" +
	"\rListLLMModels\x12 .sortedchat.ListLLMModelsRequest\x1a!.sortedchat.ListLLMModelsResponse0\x01B&Z$sortedstartup/inferenceservice/protob\x06proto3"

var (
	file_inferenceservice_proto_rawDescOnce sync.Once
	file_inferenceservice_proto_rawDescData []byte
)

func file_inferenceservice_proto_rawDescGZIP() []byte {
	file_inferenceservice_proto_rawDescOnce.Do(func() {
		file_inferenceservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inferenceservice_proto_rawDesc), len(file_inferenceservice_proto_rawDesc)))
	})
	return file_inferenceservice_proto_rawDescData
}

var file_inferenceservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_inferenceservice_proto_goTypes = []any{
	(*Model)(nil),                 // 0: sortedchat.Model
	(*DownloadModelRequest)(nil),  // 1: sortedchat.DownloadModelRequest
	(*DownloadModelResponse)(nil), // 2: sortedchat.DownloadModelResponse
	(*ListLLMModelsRequest)(nil),  // 3: sortedchat.ListLLMModelsRequest
	(*ListLLMModelsResponse)(nil), // 4: sortedchat.ListLLMModelsResponse
}
var file_inferenceservice_proto_depIdxs = []int32{
	0, // 0: sortedchat.ListLLMModelsResponse.models:type_name -> sortedchat.Model
	1, // 1: sortedchat.InferenceService.DownloadModel:input_type -> sortedchat.DownloadModelRequest
	3, // 2: sortedchat.InferenceService.ListLLMModels:input_type -> sortedchat.ListLLMModelsRequest
	2, // 3: sortedchat.InferenceService.DownloadModel:output_type -> sortedchat.DownloadModelResponse
	4, // 4: sortedchat.InferenceService.ListLLMModels:output_type -> sortedchat.ListLLMModelsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inferenceservice_proto_init() }
func file_inferenceservice_proto_init() {
	if File_inferenceservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inferenceservice_proto_rawDesc), len(file_inferenceservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inferenceservice_proto_goTypes,
		DependencyIndexes: file_inferenceservice_proto_depIdxs,
		MessageInfos:      file_inferenceservice_proto_msgTypes,
	}.Build()
	File_inferenceservice_proto = out.File
	file_inferenceservice_proto_goTypes = nil
	file_inferenceservice_proto_depIdxs = nil
}
