// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: inferenceservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Download status enum
type DownloadStatus int32

const (
	DownloadStatus_NONE        DownloadStatus = 0 // For non-downloadable models
	DownloadStatus_PENDING     DownloadStatus = 1 // Ready to download
	DownloadStatus_DOWNLOADING DownloadStatus = 2 // Currently downloading
	DownloadStatus_COMPLETED   DownloadStatus = 3 // Download completed
	DownloadStatus_FAILED      DownloadStatus = 4 // Download failed
	DownloadStatus_CANCELLING  DownloadStatus = 5 // Download cancelled
)

// Enum value maps for DownloadStatus.
var (
	DownloadStatus_name = map[int32]string{
		0: "NONE",
		1: "PENDING",
		2: "DOWNLOADING",
		3: "COMPLETED",
		4: "FAILED",
		5: "CANCELLING",
	}
	DownloadStatus_value = map[string]int32{
		"NONE":        0,
		"PENDING":     1,
		"DOWNLOADING": 2,
		"COMPLETED":   3,
		"FAILED":      4,
		"CANCELLING":  5,
	}
)

func (x DownloadStatus) Enum() *DownloadStatus {
	p := new(DownloadStatus)
	*p = x
	return p
}

func (x DownloadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownloadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_inferenceservice_proto_enumTypes[0].Descriptor()
}

func (DownloadStatus) Type() protoreflect.EnumType {
	return &file_inferenceservice_proto_enumTypes[0]
}

func (x DownloadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DownloadStatus.Descriptor instead.
func (DownloadStatus) EnumDescriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{0}
}

type DownloadProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileSize      int64                  `protobuf:"varint,1,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`            // Total file size in bytes
	Status        DownloadStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=sortedchat.DownloadStatus" json:"status,omitempty"` // Download status
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`                            // Progress percentage (0-100)
	Speed         int64                  `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`                                  // Download speed in kilobytes per second
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadProgress) Reset() {
	*x = DownloadProgress{}
	mi := &file_inferenceservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadProgress) ProtoMessage() {}

func (x *DownloadProgress) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadProgress.ProtoReflect.Descriptor instead.
func (*DownloadProgress) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadProgress) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *DownloadProgress) GetStatus() DownloadStatus {
	if x != nil {
		return x.Status
	}
	return DownloadStatus_NONE
}

func (x *DownloadProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *DownloadProgress) GetSpeed() int64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type Model struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url             string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Provider        string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	InputTokenCost  float64                `protobuf:"fixed64,5,opt,name=input_token_cost,json=inputTokenCost,proto3" json:"input_token_cost,omitempty"`
	OutputTokenCost float64                `protobuf:"fixed64,6,opt,name=output_token_cost,json=outputTokenCost,proto3" json:"output_token_cost,omitempty"`
	Progress        *DownloadProgress      `protobuf:"bytes,7,opt,name=progress,proto3" json:"progress,omitempty"`
	IsDownloaded    bool                   `protobuf:"varint,8,opt,name=is_downloaded,json=isDownloaded,proto3" json:"is_downloaded,omitempty"`
	IsDownloadable  bool                   `protobuf:"varint,9,opt,name=is_downloadable,json=isDownloadable,proto3" json:"is_downloadable,omitempty"`
	Status          DownloadStatus         `protobuf:"varint,10,opt,name=status,proto3,enum=sortedchat.DownloadStatus" json:"status,omitempty"`
	FilestoreId     string                 `protobuf:"bytes,11,opt,name=filestore_id,json=filestoreId,proto3" json:"filestore_id,omitempty"` // File path for downloadable models, null for non-downloadable
	Capabilities    *ModelCapabilities     `protobuf:"bytes,12,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	CachedTokenCost float64                `protobuf:"fixed64,13,opt,name=cached_token_cost,json=cachedTokenCost,proto3" json:"cached_token_cost,omitempty"`
	IsEnabled       bool                   `protobuf:"varint,14,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_inferenceservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{1}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Model) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Model) GetInputTokenCost() float64 {
	if x != nil {
		return x.InputTokenCost
	}
	return 0
}

func (x *Model) GetOutputTokenCost() float64 {
	if x != nil {
		return x.OutputTokenCost
	}
	return 0
}

func (x *Model) GetProgress() *DownloadProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *Model) GetIsDownloaded() bool {
	if x != nil {
		return x.IsDownloaded
	}
	return false
}

func (x *Model) GetIsDownloadable() bool {
	if x != nil {
		return x.IsDownloadable
	}
	return false
}

func (x *Model) GetStatus() DownloadStatus {
	if x != nil {
		return x.Status
	}
	return DownloadStatus_NONE
}

func (x *Model) GetFilestoreId() string {
	if x != nil {
		return x.FilestoreId
	}
	return ""
}

func (x *Model) GetCapabilities() *ModelCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Model) GetCachedTokenCost() float64 {
	if x != nil {
		return x.CachedTokenCost
	}
	return 0
}

func (x *Model) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

type ModelCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *Capability            `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Audio         *Capability            `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"`
	Video         *Capability            `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	Image         *Capability            `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Realtime      bool                   `protobuf:"varint,5,opt,name=realtime,proto3" json:"realtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelCapabilities) Reset() {
	*x = ModelCapabilities{}
	mi := &file_inferenceservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCapabilities) ProtoMessage() {}

func (x *ModelCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCapabilities.ProtoReflect.Descriptor instead.
func (*ModelCapabilities) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{2}
}

func (x *ModelCapabilities) GetText() *Capability {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *ModelCapabilities) GetAudio() *Capability {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *ModelCapabilities) GetVideo() *Capability {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *ModelCapabilities) GetImage() *Capability {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ModelCapabilities) GetRealtime() bool {
	if x != nil {
		return x.Realtime
	}
	return false
}

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         bool                   `protobuf:"varint,1,opt,name=input,proto3" json:"input,omitempty"`
	Output        bool                   `protobuf:"varint,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_inferenceservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{3}
}

func (x *Capability) GetInput() bool {
	if x != nil {
		return x.Input
	}
	return false
}

func (x *Capability) GetOutput() bool {
	if x != nil {
		return x.Output
	}
	return false
}

type DownloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadModelRequest) Reset() {
	*x = DownloadModelRequest{}
	mi := &file_inferenceservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadModelRequest) ProtoMessage() {}

func (x *DownloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadModelRequest.ProtoReflect.Descriptor instead.
func (*DownloadModelRequest) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadModelRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type DownloadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadModelResponse) Reset() {
	*x = DownloadModelResponse{}
	mi := &file_inferenceservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadModelResponse) ProtoMessage() {}

func (x *DownloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadModelResponse.ProtoReflect.Descriptor instead.
func (*DownloadModelResponse) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLLMModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMModelsRequest) Reset() {
	*x = GetLLMModelsRequest{}
	mi := &file_inferenceservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMModelsRequest) ProtoMessage() {}

func (x *GetLLMModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMModelsRequest.ProtoReflect.Descriptor instead.
func (*GetLLMModelsRequest) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{6}
}

type GetLLMModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMModelsResponse) Reset() {
	*x = GetLLMModelsResponse{}
	mi := &file_inferenceservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMModelsResponse) ProtoMessage() {}

func (x *GetLLMModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMModelsResponse.ProtoReflect.Descriptor instead.
func (*GetLLMModelsResponse) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{7}
}

func (x *GetLLMModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type CancelDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDownloadRequest) Reset() {
	*x = CancelDownloadRequest{}
	mi := &file_inferenceservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDownloadRequest) ProtoMessage() {}

func (x *CancelDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDownloadRequest.ProtoReflect.Descriptor instead.
func (*CancelDownloadRequest) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{8}
}

func (x *CancelDownloadRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type CancelDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDownloadResponse) Reset() {
	*x = CancelDownloadResponse{}
	mi := &file_inferenceservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDownloadResponse) ProtoMessage() {}

func (x *CancelDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDownloadResponse.ProtoReflect.Descriptor instead.
func (*CancelDownloadResponse) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{9}
}

func (x *CancelDownloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_inferenceservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteModelRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type DeleteModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelResponse) Reset() {
	*x = DeleteModelResponse{}
	mi := &file_inferenceservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelResponse) ProtoMessage() {}

func (x *DeleteModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inferenceservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelResponse) Descriptor() ([]byte, []int) {
	return file_inferenceservice_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_inferenceservice_proto protoreflect.FileDescriptor

const file_inferenceservice_proto_rawDesc = "" +
	"\n" +
	"\x16inferenceservice.proto\x12\n" +
	"sortedchat\"\x95\x01\n" +
	"\x10DownloadProgress\x12\x1b\n" +
	"\tfile_size\x18\x01 \x01(\x03R\bfileSize\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.sortedchat.DownloadStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x03R\x05speed\"\x9c\x04\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12(\n" +
	"\x10input_token_cost\x18\x05 \x01(\x01R\x0einputTokenCost\x12*\n" +
	"\x11output_token_cost\x18\x06 \x01(\x01R\x0foutputTokenCost\x128\n" +
	"\bprogress\x18\a \x01(\v2\x1c.sortedchat.DownloadProgressR\bprogress\x12#\n" +
	"\ris_downloaded\x18\b \x01(\bR\fisDownloaded\x12'\n" +
	"\x0fis_downloadable\x18\t \x01(\bR\x0eisDownloadable\x122\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x1a.sortedchat.DownloadStatusR\x06status\x12!\n" +
	"\ffilestore_id\x18\v \x01(\tR\vfilestoreId\x12A\n" +
	"\fcapabilities\x18\f \x01(\v2\x1d.sortedchat.ModelCapabilitiesR\fcapabilities\x12*\n" +
	"\x11cached_token_cost\x18\r \x01(\x01R\x0fcachedTokenCost\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x0e \x01(\bR\tisEnabled\"\xe5\x01\n" +
	"\x11ModelCapabilities\x12*\n" +
	"\x04text\x18\x01 \x01(\v2\x16.sortedchat.CapabilityR\x04text\x12,\n" +
	"\x05audio\x18\x02 \x01(\v2\x16.sortedchat.CapabilityR\x05audio\x12,\n" +
	"\x05video\x18\x03 \x01(\v2\x16.sortedchat.CapabilityR\x05video\x12,\n" +
	"\x05image\x18\x04 \x01(\v2\x16.sortedchat.CapabilityR\x05image\x12\x1a\n" +
	"\brealtime\x18\x05 \x01(\bR\brealtime\":\n" +
	"\n" +
	"Capability\x12\x14\n" +
	"\x05input\x18\x01 \x01(\bR\x05input\x12\x16\n" +
	"\x06output\x18\x02 \x01(\bR\x06output\"5\n" +
	"\x14DownloadModelRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\"1\n" +
	"\x15DownloadModelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x15\n" +
	"\x13GetLLMModelsRequest\"A\n" +
	"\x14GetLLMModelsResponse\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.sortedchat.ModelR\x06models\"6\n" +
	"\x15CancelDownloadRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\"2\n" +
	"\x16CancelDownloadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"3\n" +
	"\x12DeleteModelRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\"/\n" +
	"\x13DeleteModelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*c\n" +
	"\x0eDownloadStatus\x12\b\n" +
	"\x04NONE\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0f\n" +
	"\vDOWNLOADING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\x0e\n" +
	"\n" +
	"CANCELLING\x10\x052\xe6\x02\n" +
	"\x10InferenceService\x12T\n" +
	"\rDownloadModel\x12 .sortedchat.DownloadModelRequest\x1a!.sortedchat.DownloadModelResponse\x12S\n" +
	"\fGetLLMModels\x12\x1f.sortedchat.GetLLMModelsRequest\x1a .sortedchat.GetLLMModelsResponse0\x01\x12W\n" +
	"\x0eCancelDownload\x12!.sortedchat.CancelDownloadRequest\x1a\".sortedchat.CancelDownloadResponse\x12N\n" +
	"\vDeleteModel\x12\x1e.sortedchat.DeleteModelRequest\x1a\x1f.sortedchat.DeleteModelResponseB&Z$sortedstartup/inferenceservice/protob\x06proto3"

var (
	file_inferenceservice_proto_rawDescOnce sync.Once
	file_inferenceservice_proto_rawDescData []byte
)

func file_inferenceservice_proto_rawDescGZIP() []byte {
	file_inferenceservice_proto_rawDescOnce.Do(func() {
		file_inferenceservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inferenceservice_proto_rawDesc), len(file_inferenceservice_proto_rawDesc)))
	})
	return file_inferenceservice_proto_rawDescData
}

var file_inferenceservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inferenceservice_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_inferenceservice_proto_goTypes = []any{
	(DownloadStatus)(0),            // 0: sortedchat.DownloadStatus
	(*DownloadProgress)(nil),       // 1: sortedchat.DownloadProgress
	(*Model)(nil),                  // 2: sortedchat.Model
	(*ModelCapabilities)(nil),      // 3: sortedchat.ModelCapabilities
	(*Capability)(nil),             // 4: sortedchat.Capability
	(*DownloadModelRequest)(nil),   // 5: sortedchat.DownloadModelRequest
	(*DownloadModelResponse)(nil),  // 6: sortedchat.DownloadModelResponse
	(*GetLLMModelsRequest)(nil),    // 7: sortedchat.GetLLMModelsRequest
	(*GetLLMModelsResponse)(nil),   // 8: sortedchat.GetLLMModelsResponse
	(*CancelDownloadRequest)(nil),  // 9: sortedchat.CancelDownloadRequest
	(*CancelDownloadResponse)(nil), // 10: sortedchat.CancelDownloadResponse
	(*DeleteModelRequest)(nil),     // 11: sortedchat.DeleteModelRequest
	(*DeleteModelResponse)(nil),    // 12: sortedchat.DeleteModelResponse
}
var file_inferenceservice_proto_depIdxs = []int32{
	0,  // 0: sortedchat.DownloadProgress.status:type_name -> sortedchat.DownloadStatus
	1,  // 1: sortedchat.Model.progress:type_name -> sortedchat.DownloadProgress
	0,  // 2: sortedchat.Model.status:type_name -> sortedchat.DownloadStatus
	3,  // 3: sortedchat.Model.capabilities:type_name -> sortedchat.ModelCapabilities
	4,  // 4: sortedchat.ModelCapabilities.text:type_name -> sortedchat.Capability
	4,  // 5: sortedchat.ModelCapabilities.audio:type_name -> sortedchat.Capability
	4,  // 6: sortedchat.ModelCapabilities.video:type_name -> sortedchat.Capability
	4,  // 7: sortedchat.ModelCapabilities.image:type_name -> sortedchat.Capability
	2,  // 8: sortedchat.GetLLMModelsResponse.models:type_name -> sortedchat.Model
	5,  // 9: sortedchat.InferenceService.DownloadModel:input_type -> sortedchat.DownloadModelRequest
	7,  // 10: sortedchat.InferenceService.GetLLMModels:input_type -> sortedchat.GetLLMModelsRequest
	9,  // 11: sortedchat.InferenceService.CancelDownload:input_type -> sortedchat.CancelDownloadRequest
	11, // 12: sortedchat.InferenceService.DeleteModel:input_type -> sortedchat.DeleteModelRequest
	6,  // 13: sortedchat.InferenceService.DownloadModel:output_type -> sortedchat.DownloadModelResponse
	8,  // 14: sortedchat.InferenceService.GetLLMModels:output_type -> sortedchat.GetLLMModelsResponse
	10, // 15: sortedchat.InferenceService.CancelDownload:output_type -> sortedchat.CancelDownloadResponse
	12, // 16: sortedchat.InferenceService.DeleteModel:output_type -> sortedchat.DeleteModelResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_inferenceservice_proto_init() }
func file_inferenceservice_proto_init() {
	if File_inferenceservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inferenceservice_proto_rawDesc), len(file_inferenceservice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inferenceservice_proto_goTypes,
		DependencyIndexes: file_inferenceservice_proto_depIdxs,
		EnumInfos:         file_inferenceservice_proto_enumTypes,
		MessageInfos:      file_inferenceservice_proto_msgTypes,
	}.Build()
	File_inferenceservice_proto = out.File
	file_inferenceservice_proto_goTypes = nil
	file_inferenceservice_proto_depIdxs = nil
}
