// @ts-nocheck
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.29.2
 * source: inferenceservice.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "grpc-web";
import * as grpc_web_1 from "grpc-web";
export enum DownloadStatus {
    NONE = 0,
    PENDING = 1,
    DOWNLOADING = 2,
    COMPLETED = 3,
    FAILED = 4,
    CANCELLING = 5
}
export class DownloadProgress extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        file_size?: number;
        status?: DownloadStatus;
        progress?: number;
        speed?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("file_size" in data && data.file_size != undefined) {
                this.file_size = data.file_size;
            }
            if ("status" in data && data.status != undefined) {
                this.status = data.status;
            }
            if ("progress" in data && data.progress != undefined) {
                this.progress = data.progress;
            }
            if ("speed" in data && data.speed != undefined) {
                this.speed = data.speed;
            }
        }
    }
    get file_size() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set file_size(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get status() {
        return pb_1.Message.getFieldWithDefault(this, 2, DownloadStatus.NONE) as DownloadStatus;
    }
    set status(value: DownloadStatus) {
        pb_1.Message.setField(this, 2, value);
    }
    get progress() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set progress(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get speed() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set speed(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        file_size?: number;
        status?: DownloadStatus;
        progress?: number;
        speed?: number;
    }): DownloadProgress {
        const message = new DownloadProgress({});
        if (data.file_size != null) {
            message.file_size = data.file_size;
        }
        if (data.status != null) {
            message.status = data.status;
        }
        if (data.progress != null) {
            message.progress = data.progress;
        }
        if (data.speed != null) {
            message.speed = data.speed;
        }
        return message;
    }
    toObject() {
        const data: {
            file_size?: number;
            status?: DownloadStatus;
            progress?: number;
            speed?: number;
        } = {};
        if (this.file_size != null) {
            data.file_size = this.file_size;
        }
        if (this.status != null) {
            data.status = this.status;
        }
        if (this.progress != null) {
            data.progress = this.progress;
        }
        if (this.speed != null) {
            data.speed = this.speed;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.file_size != 0)
            writer.writeInt64(1, this.file_size);
        if (this.status != DownloadStatus.NONE)
            writer.writeEnum(2, this.status);
        if (this.progress != 0)
            writer.writeInt32(3, this.progress);
        if (this.speed != 0)
            writer.writeInt64(4, this.speed);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DownloadProgress {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DownloadProgress();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.file_size = reader.readInt64();
                    break;
                case 2:
                    message.status = reader.readEnum();
                    break;
                case 3:
                    message.progress = reader.readInt32();
                    break;
                case 4:
                    message.speed = reader.readInt64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): DownloadProgress {
        return DownloadProgress.deserialize(bytes);
    }
}
export class Model extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        id?: string;
        name?: string;
        url?: string;
        provider?: string;
        input_token_cost?: number;
        output_token_cost?: number;
        progress?: DownloadProgress;
        is_downloaded?: boolean;
        is_downloadable?: boolean;
        status?: DownloadStatus;
        filestore_id?: string;
        is_embedding_model?: boolean;
        is_enabled?: boolean;
        model_info?: ModelInfo;
        creator_name?: string;
        modified_by?: string;
        description?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
            if ("name" in data && data.name != undefined) {
                this.name = data.name;
            }
            if ("url" in data && data.url != undefined) {
                this.url = data.url;
            }
            if ("provider" in data && data.provider != undefined) {
                this.provider = data.provider;
            }
            if ("input_token_cost" in data && data.input_token_cost != undefined) {
                this.input_token_cost = data.input_token_cost;
            }
            if ("output_token_cost" in data && data.output_token_cost != undefined) {
                this.output_token_cost = data.output_token_cost;
            }
            if ("progress" in data && data.progress != undefined) {
                this.progress = data.progress;
            }
            if ("is_downloaded" in data && data.is_downloaded != undefined) {
                this.is_downloaded = data.is_downloaded;
            }
            if ("is_downloadable" in data && data.is_downloadable != undefined) {
                this.is_downloadable = data.is_downloadable;
            }
            if ("status" in data && data.status != undefined) {
                this.status = data.status;
            }
            if ("filestore_id" in data && data.filestore_id != undefined) {
                this.filestore_id = data.filestore_id;
            }
            if ("is_embedding_model" in data && data.is_embedding_model != undefined) {
                this.is_embedding_model = data.is_embedding_model;
            }
            if ("is_enabled" in data && data.is_enabled != undefined) {
                this.is_enabled = data.is_enabled;
            }
            if ("model_info" in data && data.model_info != undefined) {
                this.model_info = data.model_info;
            }
            if ("creator_name" in data && data.creator_name != undefined) {
                this.creator_name = data.creator_name;
            }
            if ("modified_by" in data && data.modified_by != undefined) {
                this.modified_by = data.modified_by;
            }
            if ("description" in data && data.description != undefined) {
                this.description = data.description;
            }
        }
    }
    get id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get name() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set name(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get url() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set url(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get provider() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set provider(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    get input_token_cost() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set input_token_cost(value: number) {
        pb_1.Message.setField(this, 5, value);
    }
    get output_token_cost() {
        return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set output_token_cost(value: number) {
        pb_1.Message.setField(this, 6, value);
    }
    get progress() {
        return pb_1.Message.getWrapperField(this, DownloadProgress, 7) as DownloadProgress;
    }
    set progress(value: DownloadProgress) {
        pb_1.Message.setWrapperField(this, 7, value);
    }
    get has_progress() {
        return pb_1.Message.getField(this, 7) != null;
    }
    get is_downloaded() {
        return pb_1.Message.getFieldWithDefault(this, 8, false) as boolean;
    }
    set is_downloaded(value: boolean) {
        pb_1.Message.setField(this, 8, value);
    }
    get is_downloadable() {
        return pb_1.Message.getFieldWithDefault(this, 9, false) as boolean;
    }
    set is_downloadable(value: boolean) {
        pb_1.Message.setField(this, 9, value);
    }
    get status() {
        return pb_1.Message.getFieldWithDefault(this, 10, DownloadStatus.NONE) as DownloadStatus;
    }
    set status(value: DownloadStatus) {
        pb_1.Message.setField(this, 10, value);
    }
    get filestore_id() {
        return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
    }
    set filestore_id(value: string) {
        pb_1.Message.setField(this, 11, value);
    }
    get is_embedding_model() {
        return pb_1.Message.getFieldWithDefault(this, 12, false) as boolean;
    }
    set is_embedding_model(value: boolean) {
        pb_1.Message.setField(this, 12, value);
    }
    get is_enabled() {
        return pb_1.Message.getFieldWithDefault(this, 14, false) as boolean;
    }
    set is_enabled(value: boolean) {
        pb_1.Message.setField(this, 14, value);
    }
    get model_info() {
        return pb_1.Message.getWrapperField(this, ModelInfo, 15) as ModelInfo;
    }
    set model_info(value: ModelInfo) {
        pb_1.Message.setWrapperField(this, 15, value);
    }
    get has_model_info() {
        return pb_1.Message.getField(this, 15) != null;
    }
    get creator_name() {
        return pb_1.Message.getFieldWithDefault(this, 16, "") as string;
    }
    set creator_name(value: string) {
        pb_1.Message.setField(this, 16, value);
    }
    get modified_by() {
        return pb_1.Message.getFieldWithDefault(this, 17, "") as string;
    }
    set modified_by(value: string) {
        pb_1.Message.setField(this, 17, value);
    }
    get description() {
        return pb_1.Message.getFieldWithDefault(this, 18, "") as string;
    }
    set description(value: string) {
        pb_1.Message.setField(this, 18, value);
    }
    static fromObject(data: {
        id?: string;
        name?: string;
        url?: string;
        provider?: string;
        input_token_cost?: number;
        output_token_cost?: number;
        progress?: ReturnType<typeof DownloadProgress.prototype.toObject>;
        is_downloaded?: boolean;
        is_downloadable?: boolean;
        status?: DownloadStatus;
        filestore_id?: string;
        is_embedding_model?: boolean;
        is_enabled?: boolean;
        model_info?: ReturnType<typeof ModelInfo.prototype.toObject>;
        creator_name?: string;
        modified_by?: string;
        description?: string;
    }): Model {
        const message = new Model({});
        if (data.id != null) {
            message.id = data.id;
        }
        if (data.name != null) {
            message.name = data.name;
        }
        if (data.url != null) {
            message.url = data.url;
        }
        if (data.provider != null) {
            message.provider = data.provider;
        }
        if (data.input_token_cost != null) {
            message.input_token_cost = data.input_token_cost;
        }
        if (data.output_token_cost != null) {
            message.output_token_cost = data.output_token_cost;
        }
        if (data.progress != null) {
            message.progress = DownloadProgress.fromObject(data.progress);
        }
        if (data.is_downloaded != null) {
            message.is_downloaded = data.is_downloaded;
        }
        if (data.is_downloadable != null) {
            message.is_downloadable = data.is_downloadable;
        }
        if (data.status != null) {
            message.status = data.status;
        }
        if (data.filestore_id != null) {
            message.filestore_id = data.filestore_id;
        }
        if (data.is_embedding_model != null) {
            message.is_embedding_model = data.is_embedding_model;
        }
        if (data.is_enabled != null) {
            message.is_enabled = data.is_enabled;
        }
        if (data.model_info != null) {
            message.model_info = ModelInfo.fromObject(data.model_info);
        }
        if (data.creator_name != null) {
            message.creator_name = data.creator_name;
        }
        if (data.modified_by != null) {
            message.modified_by = data.modified_by;
        }
        if (data.description != null) {
            message.description = data.description;
        }
        return message;
    }
    toObject() {
        const data: {
            id?: string;
            name?: string;
            url?: string;
            provider?: string;
            input_token_cost?: number;
            output_token_cost?: number;
            progress?: ReturnType<typeof DownloadProgress.prototype.toObject>;
            is_downloaded?: boolean;
            is_downloadable?: boolean;
            status?: DownloadStatus;
            filestore_id?: string;
            is_embedding_model?: boolean;
            is_enabled?: boolean;
            model_info?: ReturnType<typeof ModelInfo.prototype.toObject>;
            creator_name?: string;
            modified_by?: string;
            description?: string;
        } = {};
        if (this.id != null) {
            data.id = this.id;
        }
        if (this.name != null) {
            data.name = this.name;
        }
        if (this.url != null) {
            data.url = this.url;
        }
        if (this.provider != null) {
            data.provider = this.provider;
        }
        if (this.input_token_cost != null) {
            data.input_token_cost = this.input_token_cost;
        }
        if (this.output_token_cost != null) {
            data.output_token_cost = this.output_token_cost;
        }
        if (this.progress != null) {
            data.progress = this.progress.toObject();
        }
        if (this.is_downloaded != null) {
            data.is_downloaded = this.is_downloaded;
        }
        if (this.is_downloadable != null) {
            data.is_downloadable = this.is_downloadable;
        }
        if (this.status != null) {
            data.status = this.status;
        }
        if (this.filestore_id != null) {
            data.filestore_id = this.filestore_id;
        }
        if (this.is_embedding_model != null) {
            data.is_embedding_model = this.is_embedding_model;
        }
        if (this.is_enabled != null) {
            data.is_enabled = this.is_enabled;
        }
        if (this.model_info != null) {
            data.model_info = this.model_info.toObject();
        }
        if (this.creator_name != null) {
            data.creator_name = this.creator_name;
        }
        if (this.modified_by != null) {
            data.modified_by = this.modified_by;
        }
        if (this.description != null) {
            data.description = this.description;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id.length)
            writer.writeString(1, this.id);
        if (this.name.length)
            writer.writeString(2, this.name);
        if (this.url.length)
            writer.writeString(3, this.url);
        if (this.provider.length)
            writer.writeString(4, this.provider);
        if (this.input_token_cost != 0)
            writer.writeDouble(5, this.input_token_cost);
        if (this.output_token_cost != 0)
            writer.writeDouble(6, this.output_token_cost);
        if (this.has_progress)
            writer.writeMessage(7, this.progress, () => this.progress.serialize(writer));
        if (this.is_downloaded != false)
            writer.writeBool(8, this.is_downloaded);
        if (this.is_downloadable != false)
            writer.writeBool(9, this.is_downloadable);
        if (this.status != DownloadStatus.NONE)
            writer.writeEnum(10, this.status);
        if (this.filestore_id.length)
            writer.writeString(11, this.filestore_id);
        if (this.is_embedding_model != false)
            writer.writeBool(12, this.is_embedding_model);
        if (this.is_enabled != false)
            writer.writeBool(14, this.is_enabled);
        if (this.has_model_info)
            writer.writeMessage(15, this.model_info, () => this.model_info.serialize(writer));
        if (this.creator_name.length)
            writer.writeString(16, this.creator_name);
        if (this.modified_by.length)
            writer.writeString(17, this.modified_by);
        if (this.description.length)
            writer.writeString(18, this.description);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Model {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Model();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readString();
                    break;
                case 2:
                    message.name = reader.readString();
                    break;
                case 3:
                    message.url = reader.readString();
                    break;
                case 4:
                    message.provider = reader.readString();
                    break;
                case 5:
                    message.input_token_cost = reader.readDouble();
                    break;
                case 6:
                    message.output_token_cost = reader.readDouble();
                    break;
                case 7:
                    reader.readMessage(message.progress, () => message.progress = DownloadProgress.deserialize(reader));
                    break;
                case 8:
                    message.is_downloaded = reader.readBool();
                    break;
                case 9:
                    message.is_downloadable = reader.readBool();
                    break;
                case 10:
                    message.status = reader.readEnum();
                    break;
                case 11:
                    message.filestore_id = reader.readString();
                    break;
                case 12:
                    message.is_embedding_model = reader.readBool();
                    break;
                case 14:
                    message.is_enabled = reader.readBool();
                    break;
                case 15:
                    reader.readMessage(message.model_info, () => message.model_info = ModelInfo.deserialize(reader));
                    break;
                case 16:
                    message.creator_name = reader.readString();
                    break;
                case 17:
                    message.modified_by = reader.readString();
                    break;
                case 18:
                    message.description = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Model {
        return Model.deserialize(bytes);
    }
}
export class ModelInfo extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        home_page_url?: string;
        quantization?: string;
        download_size?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("home_page_url" in data && data.home_page_url != undefined) {
                this.home_page_url = data.home_page_url;
            }
            if ("quantization" in data && data.quantization != undefined) {
                this.quantization = data.quantization;
            }
            if ("download_size" in data && data.download_size != undefined) {
                this.download_size = data.download_size;
            }
        }
    }
    get home_page_url() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set home_page_url(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get quantization() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set quantization(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get download_size() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set download_size(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        home_page_url?: string;
        quantization?: string;
        download_size?: string;
    }): ModelInfo {
        const message = new ModelInfo({});
        if (data.home_page_url != null) {
            message.home_page_url = data.home_page_url;
        }
        if (data.quantization != null) {
            message.quantization = data.quantization;
        }
        if (data.download_size != null) {
            message.download_size = data.download_size;
        }
        return message;
    }
    toObject() {
        const data: {
            home_page_url?: string;
            quantization?: string;
            download_size?: string;
        } = {};
        if (this.home_page_url != null) {
            data.home_page_url = this.home_page_url;
        }
        if (this.quantization != null) {
            data.quantization = this.quantization;
        }
        if (this.download_size != null) {
            data.download_size = this.download_size;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.home_page_url.length)
            writer.writeString(2, this.home_page_url);
        if (this.quantization.length)
            writer.writeString(3, this.quantization);
        if (this.download_size.length)
            writer.writeString(4, this.download_size);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ModelInfo {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ModelInfo();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 2:
                    message.home_page_url = reader.readString();
                    break;
                case 3:
                    message.quantization = reader.readString();
                    break;
                case 4:
                    message.download_size = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ModelInfo {
        return ModelInfo.deserialize(bytes);
    }
}
export class DownloadModelRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        model_id?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("model_id" in data && data.model_id != undefined) {
                this.model_id = data.model_id;
            }
        }
    }
    get model_id() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set model_id(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        model_id?: string;
    }): DownloadModelRequest {
        const message = new DownloadModelRequest({});
        if (data.model_id != null) {
            message.model_id = data.model_id;
        }
        return message;
    }
    toObject() {
        const data: {
            model_id?: string;
        } = {};
        if (this.model_id != null) {
            data.model_id = this.model_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.model_id.length)
            writer.writeString(2, this.model_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DownloadModelRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DownloadModelRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 2:
                    message.model_id = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): DownloadModelRequest {
        return DownloadModelRequest.deserialize(bytes);
    }
}
export class DownloadModelResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        message?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("message" in data && data.message != undefined) {
                this.message = data.message;
            }
        }
    }
    get message() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set message(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        message?: string;
    }): DownloadModelResponse {
        const message = new DownloadModelResponse({});
        if (data.message != null) {
            message.message = data.message;
        }
        return message;
    }
    toObject() {
        const data: {
            message?: string;
        } = {};
        if (this.message != null) {
            data.message = this.message;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.message.length)
            writer.writeString(1, this.message);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DownloadModelResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DownloadModelResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.message = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): DownloadModelResponse {
        return DownloadModelResponse.deserialize(bytes);
    }
}
export class GetLLMModelsRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {}) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") { }
    }
    static fromObject(data: {}): GetLLMModelsRequest {
        const message = new GetLLMModelsRequest({});
        return message;
    }
    toObject() {
        const data: {} = {};
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetLLMModelsRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetLLMModelsRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetLLMModelsRequest {
        return GetLLMModelsRequest.deserialize(bytes);
    }
}
export class GetLLMModelsResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        models?: Model[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("models" in data && data.models != undefined) {
                this.models = data.models;
            }
        }
    }
    get models() {
        return pb_1.Message.getRepeatedWrapperField(this, Model, 1) as Model[];
    }
    set models(value: Model[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    static fromObject(data: {
        models?: ReturnType<typeof Model.prototype.toObject>[];
    }): GetLLMModelsResponse {
        const message = new GetLLMModelsResponse({});
        if (data.models != null) {
            message.models = data.models.map(item => Model.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            models?: ReturnType<typeof Model.prototype.toObject>[];
        } = {};
        if (this.models != null) {
            data.models = this.models.map((item: Model) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.models.length)
            writer.writeRepeatedMessage(1, this.models, (item: Model) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetLLMModelsResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetLLMModelsResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.models, () => pb_1.Message.addToRepeatedWrapperField(message, 1, Model.deserialize(reader), Model));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetLLMModelsResponse {
        return GetLLMModelsResponse.deserialize(bytes);
    }
}
export class CancelDownloadRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        model_id?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("model_id" in data && data.model_id != undefined) {
                this.model_id = data.model_id;
            }
        }
    }
    get model_id() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set model_id(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        model_id?: string;
    }): CancelDownloadRequest {
        const message = new CancelDownloadRequest({});
        if (data.model_id != null) {
            message.model_id = data.model_id;
        }
        return message;
    }
    toObject() {
        const data: {
            model_id?: string;
        } = {};
        if (this.model_id != null) {
            data.model_id = this.model_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.model_id.length)
            writer.writeString(2, this.model_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CancelDownloadRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CancelDownloadRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 2:
                    message.model_id = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): CancelDownloadRequest {
        return CancelDownloadRequest.deserialize(bytes);
    }
}
export class CancelDownloadResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        message?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("message" in data && data.message != undefined) {
                this.message = data.message;
            }
        }
    }
    get message() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set message(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        message?: string;
    }): CancelDownloadResponse {
        const message = new CancelDownloadResponse({});
        if (data.message != null) {
            message.message = data.message;
        }
        return message;
    }
    toObject() {
        const data: {
            message?: string;
        } = {};
        if (this.message != null) {
            data.message = this.message;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.message.length)
            writer.writeString(1, this.message);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CancelDownloadResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CancelDownloadResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.message = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): CancelDownloadResponse {
        return CancelDownloadResponse.deserialize(bytes);
    }
}
export class DeleteModelRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        model_id?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("model_id" in data && data.model_id != undefined) {
                this.model_id = data.model_id;
            }
        }
    }
    get model_id() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set model_id(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        model_id?: string;
    }): DeleteModelRequest {
        const message = new DeleteModelRequest({});
        if (data.model_id != null) {
            message.model_id = data.model_id;
        }
        return message;
    }
    toObject() {
        const data: {
            model_id?: string;
        } = {};
        if (this.model_id != null) {
            data.model_id = this.model_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.model_id.length)
            writer.writeString(2, this.model_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeleteModelRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeleteModelRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 2:
                    message.model_id = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): DeleteModelRequest {
        return DeleteModelRequest.deserialize(bytes);
    }
}
export class DeleteModelResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        message?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("message" in data && data.message != undefined) {
                this.message = data.message;
            }
        }
    }
    get message() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set message(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        message?: string;
    }): DeleteModelResponse {
        const message = new DeleteModelResponse({});
        if (data.message != null) {
            message.message = data.message;
        }
        return message;
    }
    toObject() {
        const data: {
            message?: string;
        } = {};
        if (this.message != null) {
            data.message = this.message;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.message.length)
            writer.writeString(1, this.message);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeleteModelResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeleteModelResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.message = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): DeleteModelResponse {
        return DeleteModelResponse.deserialize(bytes);
    }
}
// Server-side service class removed for client-side compatibility
export class InferenceServiceClient {
    private _address: string;
    private _client: grpc_web_1.GrpcWebClientBase;
    constructor(address: string, credentials?: Object, options?: grpc_web_1.GrpcWebClientBaseOptions) {
        if (!options)
            options = {};
        options.format = options.format || "text";
        this._address = address;
        this._client = new grpc_web_1.GrpcWebClientBase(options);
    }
    private static DownloadModel = new grpc_web_1.MethodDescriptor<DownloadModelRequest, DownloadModelResponse>("/sortedchat.InferenceService/DownloadModel", grpc_web_1.MethodType.UNARY, DownloadModelRequest, DownloadModelResponse, (message: DownloadModelRequest) => message.serialize(), DownloadModelResponse.deserialize);
    DownloadModel(message: DownloadModelRequest, metadata: grpc_web_1.Metadata | null) {
        return this._client.thenableCall<DownloadModelRequest, DownloadModelResponse>(this._address + "/sortedchat.InferenceService/DownloadModel", message, metadata || {}, InferenceServiceClient.DownloadModel);
    }
    private static GetLLMModels = new grpc_web_1.MethodDescriptor<GetLLMModelsRequest, GetLLMModelsResponse>("/sortedchat.InferenceService/GetLLMModels", grpc_web_1.MethodType.SERVER_STREAMING, GetLLMModelsRequest, GetLLMModelsResponse, (message: GetLLMModelsRequest) => message.serialize(), GetLLMModelsResponse.deserialize);
    GetLLMModels(message: GetLLMModelsRequest, metadata: grpc_web_1.Metadata | null) {
        return this._client.serverStreaming(this._address + "/sortedchat.InferenceService/GetLLMModels", message, metadata || {}, InferenceServiceClient.GetLLMModels);
    }
    private static CancelDownload = new grpc_web_1.MethodDescriptor<CancelDownloadRequest, CancelDownloadResponse>("/sortedchat.InferenceService/CancelDownload", grpc_web_1.MethodType.UNARY, CancelDownloadRequest, CancelDownloadResponse, (message: CancelDownloadRequest) => message.serialize(), CancelDownloadResponse.deserialize);
    CancelDownload(message: CancelDownloadRequest, metadata: grpc_web_1.Metadata | null) {
        return this._client.thenableCall<CancelDownloadRequest, CancelDownloadResponse>(this._address + "/sortedchat.InferenceService/CancelDownload", message, metadata || {}, InferenceServiceClient.CancelDownload);
    }
    private static DeleteModel = new grpc_web_1.MethodDescriptor<DeleteModelRequest, DeleteModelResponse>("/sortedchat.InferenceService/DeleteModel", grpc_web_1.MethodType.UNARY, DeleteModelRequest, DeleteModelResponse, (message: DeleteModelRequest) => message.serialize(), DeleteModelResponse.deserialize);
    DeleteModel(message: DeleteModelRequest, metadata: grpc_web_1.Metadata | null) {
        return this._client.thenableCall<DeleteModelRequest, DeleteModelResponse>(this._address + "/sortedchat.InferenceService/DeleteModel", message, metadata || {}, InferenceServiceClient.DeleteModel);
    }
}
