// @ts-nocheck
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.0
 * source: inferenceservice.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "grpc-web";
import * as grpc_web_1 from "grpc-web";
export enum DownloadStatus {
    NONE = 0,
    PENDING = 1,
    DOWNLOADING = 2,
    COMPLETED = 3,
    FAILED = 4,
    CANCELLING = 5
}
export class ChatRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        text?: string;
        chatId?: string;
        model?: string;
        project_context?: ProjectContext;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("text" in data && data.text != undefined) {
                this.text = data.text;
            }
            if ("chatId" in data && data.chatId != undefined) {
                this.chatId = data.chatId;
            }
            if ("model" in data && data.model != undefined) {
                this.model = data.model;
            }
            if ("project_context" in data && data.project_context != undefined) {
                this.project_context = data.project_context;
            }
        }
    }
    get text() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set text(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get chatId() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set chatId(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get model() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set model(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get project_context() {
        return pb_1.Message.getWrapperField(this, ProjectContext, 4) as ProjectContext;
    }
    set project_context(value: ProjectContext) {
        pb_1.Message.setWrapperField(this, 4, value);
    }
    get has_project_context() {
        return pb_1.Message.getField(this, 4) != null;
    }
    static fromObject(data: {
        text?: string;
        chatId?: string;
        model?: string;
        project_context?: ReturnType<typeof ProjectContext.prototype.toObject>;
    }): ChatRequest {
        const message = new ChatRequest({});
        if (data.text != null) {
            message.text = data.text;
        }
        if (data.chatId != null) {
            message.chatId = data.chatId;
        }
        if (data.model != null) {
            message.model = data.model;
        }
        if (data.project_context != null) {
            message.project_context = ProjectContext.fromObject(data.project_context);
        }
        return message;
    }
    toObject() {
        const data: {
            text?: string;
            chatId?: string;
            model?: string;
            project_context?: ReturnType<typeof ProjectContext.prototype.toObject>;
        } = {};
        if (this.text != null) {
            data.text = this.text;
        }
        if (this.chatId != null) {
            data.chatId = this.chatId;
        }
        if (this.model != null) {
            data.model = this.model;
        }
        if (this.project_context != null) {
            data.project_context = this.project_context.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.text.length)
            writer.writeString(1, this.text);
        if (this.chatId.length)
            writer.writeString(2, this.chatId);
        if (this.model.length)
            writer.writeString(3, this.model);
        if (this.has_project_context)
            writer.writeMessage(4, this.project_context, () => this.project_context.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ChatRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ChatRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.text = reader.readString();
                    break;
                case 2:
                    message.chatId = reader.readString();
                    break;
                case 3:
                    message.model = reader.readString();
                    break;
                case 4:
                    reader.readMessage(message.project_context, () => message.project_context = ProjectContext.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ChatRequest {
        return ChatRequest.deserialize(bytes);
    }
}
export class ProjectContext extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        project_id?: string;
        rag_enabled?: boolean;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("project_id" in data && data.project_id != undefined) {
                this.project_id = data.project_id;
            }
            if ("rag_enabled" in data && data.rag_enabled != undefined) {
                this.rag_enabled = data.rag_enabled;
            }
        }
    }
    get project_id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set project_id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get rag_enabled() {
        return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
    }
    set rag_enabled(value: boolean) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        project_id?: string;
        rag_enabled?: boolean;
    }): ProjectContext {
        const message = new ProjectContext({});
        if (data.project_id != null) {
            message.project_id = data.project_id;
        }
        if (data.rag_enabled != null) {
            message.rag_enabled = data.rag_enabled;
        }
        return message;
    }
    toObject() {
        const data: {
            project_id?: string;
            rag_enabled?: boolean;
        } = {};
        if (this.project_id != null) {
            data.project_id = this.project_id;
        }
        if (this.rag_enabled != null) {
            data.rag_enabled = this.rag_enabled;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.project_id.length)
            writer.writeString(1, this.project_id);
        if (this.rag_enabled != false)
            writer.writeBool(2, this.rag_enabled);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProjectContext {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ProjectContext();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.project_id = reader.readString();
                    break;
                case 2:
                    message.rag_enabled = reader.readBool();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ProjectContext {
        return ProjectContext.deserialize(bytes);
    }
}
export class ChatResponse extends pb_1.Message {
    #one_of_decls: number[][] = [[1, 2, 3, 4, 5]];
    constructor(data?: any[] | ({} & (({
        text?: string;
        summary?: never;
        request_message_id?: never;
        document_reference?: never;
        chat_metadata?: never;
    } | {
        text?: never;
        summary?: ResponseSummary;
        request_message_id?: never;
        document_reference?: never;
        chat_metadata?: never;
    } | {
        text?: never;
        summary?: never;
        request_message_id?: string;
        document_reference?: never;
        chat_metadata?: never;
    } | {
        text?: never;
        summary?: never;
        request_message_id?: never;
        document_reference?: RAGDocumentReferenceSummaryList;
        chat_metadata?: never;
    } | {
        text?: never;
        summary?: never;
        request_message_id?: never;
        document_reference?: never;
        chat_metadata?: ChatInfo;
    })))) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("text" in data && data.text != undefined) {
                this.text = data.text;
            }
            if ("summary" in data && data.summary != undefined) {
                this.summary = data.summary;
            }
            if ("request_message_id" in data && data.request_message_id != undefined) {
                this.request_message_id = data.request_message_id;
            }
            if ("document_reference" in data && data.document_reference != undefined) {
                this.document_reference = data.document_reference;
            }
            if ("chat_metadata" in data && data.chat_metadata != undefined) {
                this.chat_metadata = data.chat_metadata;
            }
        }
    }
    get text() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set text(value: string) {
        pb_1.Message.setOneofField(this, 1, this.#one_of_decls[0], value);
    }
    get has_text() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get summary() {
        return pb_1.Message.getWrapperField(this, ResponseSummary, 2) as ResponseSummary;
    }
    set summary(value: ResponseSummary) {
        pb_1.Message.setOneofWrapperField(this, 2, this.#one_of_decls[0], value);
    }
    get has_summary() {
        return pb_1.Message.getField(this, 2) != null;
    }
    get request_message_id() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set request_message_id(value: string) {
        pb_1.Message.setOneofField(this, 3, this.#one_of_decls[0], value);
    }
    get has_request_message_id() {
        return pb_1.Message.getField(this, 3) != null;
    }
    get document_reference() {
        return pb_1.Message.getWrapperField(this, RAGDocumentReferenceSummaryList, 4) as RAGDocumentReferenceSummaryList;
    }
    set document_reference(value: RAGDocumentReferenceSummaryList) {
        pb_1.Message.setOneofWrapperField(this, 4, this.#one_of_decls[0], value);
    }
    get has_document_reference() {
        return pb_1.Message.getField(this, 4) != null;
    }
    get chat_metadata() {
        return pb_1.Message.getWrapperField(this, ChatInfo, 5) as ChatInfo;
    }
    set chat_metadata(value: ChatInfo) {
        pb_1.Message.setOneofWrapperField(this, 5, this.#one_of_decls[0], value);
    }
    get has_chat_metadata() {
        return pb_1.Message.getField(this, 5) != null;
    }
    get response() {
        const cases: {
            [index: number]: "none" | "text" | "summary" | "request_message_id" | "document_reference" | "chat_metadata";
        } = {
            0: "none",
            1: "text",
            2: "summary",
            3: "request_message_id",
            4: "document_reference",
            5: "chat_metadata"
        };
        return cases[pb_1.Message.computeOneofCase(this, [1, 2, 3, 4, 5])];
    }
    static fromObject(data: {
        text?: string;
        summary?: ReturnType<typeof ResponseSummary.prototype.toObject>;
        request_message_id?: string;
        document_reference?: ReturnType<typeof RAGDocumentReferenceSummaryList.prototype.toObject>;
        chat_metadata?: ReturnType<typeof ChatInfo.prototype.toObject>;
    }): ChatResponse {
        const message = new ChatResponse({});
        if (data.text != null) {
            message.text = data.text;
        }
        if (data.summary != null) {
            message.summary = ResponseSummary.fromObject(data.summary);
        }
        if (data.request_message_id != null) {
            message.request_message_id = data.request_message_id;
        }
        if (data.document_reference != null) {
            message.document_reference = RAGDocumentReferenceSummaryList.fromObject(data.document_reference);
        }
        if (data.chat_metadata != null) {
            message.chat_metadata = ChatInfo.fromObject(data.chat_metadata);
        }
        return message;
    }
    toObject() {
        const data: {
            text?: string;
            summary?: ReturnType<typeof ResponseSummary.prototype.toObject>;
            request_message_id?: string;
            document_reference?: ReturnType<typeof RAGDocumentReferenceSummaryList.prototype.toObject>;
            chat_metadata?: ReturnType<typeof ChatInfo.prototype.toObject>;
        } = {};
        if (this.text != null) {
            data.text = this.text;
        }
        if (this.summary != null) {
            data.summary = this.summary.toObject();
        }
        if (this.request_message_id != null) {
            data.request_message_id = this.request_message_id;
        }
        if (this.document_reference != null) {
            data.document_reference = this.document_reference.toObject();
        }
        if (this.chat_metadata != null) {
            data.chat_metadata = this.chat_metadata.toObject();
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_text)
            writer.writeString(1, this.text);
        if (this.has_summary)
            writer.writeMessage(2, this.summary, () => this.summary.serialize(writer));
        if (this.has_request_message_id)
            writer.writeString(3, this.request_message_id);
        if (this.has_document_reference)
            writer.writeMessage(4, this.document_reference, () => this.document_reference.serialize(writer));
        if (this.has_chat_metadata)
            writer.writeMessage(5, this.chat_metadata, () => this.chat_metadata.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ChatResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ChatResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.text = reader.readString();
                    break;
                case 2:
                    reader.readMessage(message.summary, () => message.summary = ResponseSummary.deserialize(reader));
                    break;
                case 3:
                    message.request_message_id = reader.readString();
                    break;
                case 4:
                    reader.readMessage(message.document_reference, () => message.document_reference = RAGDocumentReferenceSummaryList.deserialize(reader));
                    break;
                case 5:
                    reader.readMessage(message.chat_metadata, () => message.chat_metadata = ChatInfo.deserialize(reader));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ChatResponse {
        return ChatResponse.deserialize(bytes);
    }
}
export class RAGDocumentReferenceSummaryList extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        summary?: RAGDocumentReferenceSummaryListSummary[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("summary" in data && data.summary != undefined) {
                this.summary = data.summary;
            }
        }
    }
    get summary() {
        return pb_1.Message.getRepeatedWrapperField(this, RAGDocumentReferenceSummaryListSummary, 1) as RAGDocumentReferenceSummaryListSummary[];
    }
    set summary(value: RAGDocumentReferenceSummaryListSummary[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    static fromObject(data: {
        summary?: ReturnType<typeof RAGDocumentReferenceSummaryListSummary.prototype.toObject>[];
    }): RAGDocumentReferenceSummaryList {
        const message = new RAGDocumentReferenceSummaryList({});
        if (data.summary != null) {
            message.summary = data.summary.map(item => RAGDocumentReferenceSummaryListSummary.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            summary?: ReturnType<typeof RAGDocumentReferenceSummaryListSummary.prototype.toObject>[];
        } = {};
        if (this.summary != null) {
            data.summary = this.summary.map((item: RAGDocumentReferenceSummaryListSummary) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.summary.length)
            writer.writeRepeatedMessage(1, this.summary, (item: RAGDocumentReferenceSummaryListSummary) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RAGDocumentReferenceSummaryList {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RAGDocumentReferenceSummaryList();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.summary, () => pb_1.Message.addToRepeatedWrapperField(message, 1, RAGDocumentReferenceSummaryListSummary.deserialize(reader), RAGDocumentReferenceSummaryListSummary));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): RAGDocumentReferenceSummaryList {
        return RAGDocumentReferenceSummaryList.deserialize(bytes);
    }
}
export class RAGDocumentReferenceSummaryListSummary extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        doc_id?: string;
        file_name?: string;
        chunkCount?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("doc_id" in data && data.doc_id != undefined) {
                this.doc_id = data.doc_id;
            }
            if ("file_name" in data && data.file_name != undefined) {
                this.file_name = data.file_name;
            }
            if ("chunkCount" in data && data.chunkCount != undefined) {
                this.chunkCount = data.chunkCount;
            }
        }
    }
    get doc_id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set doc_id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get file_name() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set file_name(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get chunkCount() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set chunkCount(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data: {
        doc_id?: string;
        file_name?: string;
        chunkCount?: number;
    }): RAGDocumentReferenceSummaryListSummary {
        const message = new RAGDocumentReferenceSummaryListSummary({});
        if (data.doc_id != null) {
            message.doc_id = data.doc_id;
        }
        if (data.file_name != null) {
            message.file_name = data.file_name;
        }
        if (data.chunkCount != null) {
            message.chunkCount = data.chunkCount;
        }
        return message;
    }
    toObject() {
        const data: {
            doc_id?: string;
            file_name?: string;
            chunkCount?: number;
        } = {};
        if (this.doc_id != null) {
            data.doc_id = this.doc_id;
        }
        if (this.file_name != null) {
            data.file_name = this.file_name;
        }
        if (this.chunkCount != null) {
            data.chunkCount = this.chunkCount;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.doc_id.length)
            writer.writeString(1, this.doc_id);
        if (this.file_name.length)
            writer.writeString(2, this.file_name);
        if (this.chunkCount != 0)
            writer.writeInt32(3, this.chunkCount);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RAGDocumentReferenceSummaryListSummary {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RAGDocumentReferenceSummaryListSummary();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.doc_id = reader.readString();
                    break;
                case 2:
                    message.file_name = reader.readString();
                    break;
                case 3:
                    message.chunkCount = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): RAGDocumentReferenceSummaryListSummary {
        return RAGDocumentReferenceSummaryListSummary.deserialize(bytes);
    }
}
export class RAGDocumentReference extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        doc_id?: string;
        file_name?: string;
        Chunks?: RAGDocumentReferenceChunk[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("doc_id" in data && data.doc_id != undefined) {
                this.doc_id = data.doc_id;
            }
            if ("file_name" in data && data.file_name != undefined) {
                this.file_name = data.file_name;
            }
            if ("Chunks" in data && data.Chunks != undefined) {
                this.Chunks = data.Chunks;
            }
        }
    }
    get doc_id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set doc_id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get file_name() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set file_name(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get Chunks() {
        return pb_1.Message.getRepeatedWrapperField(this, RAGDocumentReferenceChunk, 3) as RAGDocumentReferenceChunk[];
    }
    set Chunks(value: RAGDocumentReferenceChunk[]) {
        pb_1.Message.setRepeatedWrapperField(this, 3, value);
    }
    static fromObject(data: {
        doc_id?: string;
        file_name?: string;
        Chunks?: ReturnType<typeof RAGDocumentReferenceChunk.prototype.toObject>[];
    }): RAGDocumentReference {
        const message = new RAGDocumentReference({});
        if (data.doc_id != null) {
            message.doc_id = data.doc_id;
        }
        if (data.file_name != null) {
            message.file_name = data.file_name;
        }
        if (data.Chunks != null) {
            message.Chunks = data.Chunks.map(item => RAGDocumentReferenceChunk.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            doc_id?: string;
            file_name?: string;
            Chunks?: ReturnType<typeof RAGDocumentReferenceChunk.prototype.toObject>[];
        } = {};
        if (this.doc_id != null) {
            data.doc_id = this.doc_id;
        }
        if (this.file_name != null) {
            data.file_name = this.file_name;
        }
        if (this.Chunks != null) {
            data.Chunks = this.Chunks.map((item: RAGDocumentReferenceChunk) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.doc_id.length)
            writer.writeString(1, this.doc_id);
        if (this.file_name.length)
            writer.writeString(2, this.file_name);
        if (this.Chunks.length)
            writer.writeRepeatedMessage(3, this.Chunks, (item: RAGDocumentReferenceChunk) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RAGDocumentReference {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RAGDocumentReference();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.doc_id = reader.readString();
                    break;
                case 2:
                    message.file_name = reader.readString();
                    break;
                case 3:
                    reader.readMessage(message.Chunks, () => pb_1.Message.addToRepeatedWrapperField(message, 3, RAGDocumentReferenceChunk.deserialize(reader), RAGDocumentReferenceChunk));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): RAGDocumentReference {
        return RAGDocumentReference.deserialize(bytes);
    }
}
export class RAGDocumentReferenceChunk extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        chunk_text?: string;
        start_byte?: number;
        end_byte?: number;
        simillarity?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("chunk_text" in data && data.chunk_text != undefined) {
                this.chunk_text = data.chunk_text;
            }
            if ("start_byte" in data && data.start_byte != undefined) {
                this.start_byte = data.start_byte;
            }
            if ("end_byte" in data && data.end_byte != undefined) {
                this.end_byte = data.end_byte;
            }
            if ("simillarity" in data && data.simillarity != undefined) {
                this.simillarity = data.simillarity;
            }
        }
    }
    get chunk_text() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set chunk_text(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get start_byte() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set start_byte(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    get end_byte() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set end_byte(value: number) {
        pb_1.Message.setField(this, 5, value);
    }
    get simillarity() {
        return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set simillarity(value: number) {
        pb_1.Message.setField(this, 6, value);
    }
    static fromObject(data: {
        chunk_text?: string;
        start_byte?: number;
        end_byte?: number;
        simillarity?: number;
    }): RAGDocumentReferenceChunk {
        const message = new RAGDocumentReferenceChunk({});
        if (data.chunk_text != null) {
            message.chunk_text = data.chunk_text;
        }
        if (data.start_byte != null) {
            message.start_byte = data.start_byte;
        }
        if (data.end_byte != null) {
            message.end_byte = data.end_byte;
        }
        if (data.simillarity != null) {
            message.simillarity = data.simillarity;
        }
        return message;
    }
    toObject() {
        const data: {
            chunk_text?: string;
            start_byte?: number;
            end_byte?: number;
            simillarity?: number;
        } = {};
        if (this.chunk_text != null) {
            data.chunk_text = this.chunk_text;
        }
        if (this.start_byte != null) {
            data.start_byte = this.start_byte;
        }
        if (this.end_byte != null) {
            data.end_byte = this.end_byte;
        }
        if (this.simillarity != null) {
            data.simillarity = this.simillarity;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.chunk_text.length)
            writer.writeString(3, this.chunk_text);
        if (this.start_byte != 0)
            writer.writeInt32(4, this.start_byte);
        if (this.end_byte != 0)
            writer.writeInt32(5, this.end_byte);
        if (this.simillarity != 0)
            writer.writeFloat(6, this.simillarity);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RAGDocumentReferenceChunk {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RAGDocumentReferenceChunk();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 3:
                    message.chunk_text = reader.readString();
                    break;
                case 4:
                    message.start_byte = reader.readInt32();
                    break;
                case 5:
                    message.end_byte = reader.readInt32();
                    break;
                case 6:
                    message.simillarity = reader.readFloat();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): RAGDocumentReferenceChunk {
        return RAGDocumentReferenceChunk.deserialize(bytes);
    }
}
export class ResponseSummary extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        message_id?: string;
        model?: string;
        input_tokens?: number;
        output_tokens?: number;
        cached_tokens?: number;
        cost?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("message_id" in data && data.message_id != undefined) {
                this.message_id = data.message_id;
            }
            if ("model" in data && data.model != undefined) {
                this.model = data.model;
            }
            if ("input_tokens" in data && data.input_tokens != undefined) {
                this.input_tokens = data.input_tokens;
            }
            if ("output_tokens" in data && data.output_tokens != undefined) {
                this.output_tokens = data.output_tokens;
            }
            if ("cached_tokens" in data && data.cached_tokens != undefined) {
                this.cached_tokens = data.cached_tokens;
            }
            if ("cost" in data && data.cost != undefined) {
                this.cost = data.cost;
            }
        }
    }
    get message_id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set message_id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get model() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set model(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get input_tokens() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set input_tokens(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get output_tokens() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set output_tokens(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    get cached_tokens() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set cached_tokens(value: number) {
        pb_1.Message.setField(this, 5, value);
    }
    get cost() {
        return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set cost(value: number) {
        pb_1.Message.setField(this, 6, value);
    }
    static fromObject(data: {
        message_id?: string;
        model?: string;
        input_tokens?: number;
        output_tokens?: number;
        cached_tokens?: number;
        cost?: number;
    }): ResponseSummary {
        const message = new ResponseSummary({});
        if (data.message_id != null) {
            message.message_id = data.message_id;
        }
        if (data.model != null) {
            message.model = data.model;
        }
        if (data.input_tokens != null) {
            message.input_tokens = data.input_tokens;
        }
        if (data.output_tokens != null) {
            message.output_tokens = data.output_tokens;
        }
        if (data.cached_tokens != null) {
            message.cached_tokens = data.cached_tokens;
        }
        if (data.cost != null) {
            message.cost = data.cost;
        }
        return message;
    }
    toObject() {
        const data: {
            message_id?: string;
            model?: string;
            input_tokens?: number;
            output_tokens?: number;
            cached_tokens?: number;
            cost?: number;
        } = {};
        if (this.message_id != null) {
            data.message_id = this.message_id;
        }
        if (this.model != null) {
            data.model = this.model;
        }
        if (this.input_tokens != null) {
            data.input_tokens = this.input_tokens;
        }
        if (this.output_tokens != null) {
            data.output_tokens = this.output_tokens;
        }
        if (this.cached_tokens != null) {
            data.cached_tokens = this.cached_tokens;
        }
        if (this.cost != null) {
            data.cost = this.cost;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.message_id.length)
            writer.writeString(1, this.message_id);
        if (this.model.length)
            writer.writeString(2, this.model);
        if (this.input_tokens != 0)
            writer.writeInt32(3, this.input_tokens);
        if (this.output_tokens != 0)
            writer.writeInt32(4, this.output_tokens);
        if (this.cached_tokens != 0)
            writer.writeInt32(5, this.cached_tokens);
        if (this.cost != 0)
            writer.writeFloat(6, this.cost);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ResponseSummary {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ResponseSummary();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.message_id = reader.readString();
                    break;
                case 2:
                    message.model = reader.readString();
                    break;
                case 3:
                    message.input_tokens = reader.readInt32();
                    break;
                case 4:
                    message.output_tokens = reader.readInt32();
                    break;
                case 5:
                    message.cached_tokens = reader.readInt32();
                    break;
                case 6:
                    message.cost = reader.readFloat();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ResponseSummary {
        return ResponseSummary.deserialize(bytes);
    }
}
export class ChatInfo extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        chatId?: string;
        name?: string;
        cost?: number;
        input_token_count?: number;
        output_token_count?: number;
        cached_token_count?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("chatId" in data && data.chatId != undefined) {
                this.chatId = data.chatId;
            }
            if ("name" in data && data.name != undefined) {
                this.name = data.name;
            }
            if ("cost" in data && data.cost != undefined) {
                this.cost = data.cost;
            }
            if ("input_token_count" in data && data.input_token_count != undefined) {
                this.input_token_count = data.input_token_count;
            }
            if ("output_token_count" in data && data.output_token_count != undefined) {
                this.output_token_count = data.output_token_count;
            }
            if ("cached_token_count" in data && data.cached_token_count != undefined) {
                this.cached_token_count = data.cached_token_count;
            }
        }
    }
    get chatId() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set chatId(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get name() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set name(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get cost() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set cost(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get input_token_count() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set input_token_count(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    get output_token_count() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set output_token_count(value: number) {
        pb_1.Message.setField(this, 5, value);
    }
    get cached_token_count() {
        return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set cached_token_count(value: number) {
        pb_1.Message.setField(this, 6, value);
    }
    static fromObject(data: {
        chatId?: string;
        name?: string;
        cost?: number;
        input_token_count?: number;
        output_token_count?: number;
        cached_token_count?: number;
    }): ChatInfo {
        const message = new ChatInfo({});
        if (data.chatId != null) {
            message.chatId = data.chatId;
        }
        if (data.name != null) {
            message.name = data.name;
        }
        if (data.cost != null) {
            message.cost = data.cost;
        }
        if (data.input_token_count != null) {
            message.input_token_count = data.input_token_count;
        }
        if (data.output_token_count != null) {
            message.output_token_count = data.output_token_count;
        }
        if (data.cached_token_count != null) {
            message.cached_token_count = data.cached_token_count;
        }
        return message;
    }
    toObject() {
        const data: {
            chatId?: string;
            name?: string;
            cost?: number;
            input_token_count?: number;
            output_token_count?: number;
            cached_token_count?: number;
        } = {};
        if (this.chatId != null) {
            data.chatId = this.chatId;
        }
        if (this.name != null) {
            data.name = this.name;
        }
        if (this.cost != null) {
            data.cost = this.cost;
        }
        if (this.input_token_count != null) {
            data.input_token_count = this.input_token_count;
        }
        if (this.output_token_count != null) {
            data.output_token_count = this.output_token_count;
        }
        if (this.cached_token_count != null) {
            data.cached_token_count = this.cached_token_count;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.chatId.length)
            writer.writeString(1, this.chatId);
        if (this.name.length)
            writer.writeString(2, this.name);
        if (this.cost != 0)
            writer.writeFloat(3, this.cost);
        if (this.input_token_count != 0)
            writer.writeInt32(4, this.input_token_count);
        if (this.output_token_count != 0)
            writer.writeInt32(5, this.output_token_count);
        if (this.cached_token_count != 0)
            writer.writeInt32(6, this.cached_token_count);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ChatInfo {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ChatInfo();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.chatId = reader.readString();
                    break;
                case 2:
                    message.name = reader.readString();
                    break;
                case 3:
                    message.cost = reader.readFloat();
                    break;
                case 4:
                    message.input_token_count = reader.readInt32();
                    break;
                case 5:
                    message.output_token_count = reader.readInt32();
                    break;
                case 6:
                    message.cached_token_count = reader.readInt32();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): ChatInfo {
        return ChatInfo.deserialize(bytes);
    }
}
export class DownloadProgress extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        file_size?: number;
        status?: DownloadStatus;
        progress?: number;
        speed?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("file_size" in data && data.file_size != undefined) {
                this.file_size = data.file_size;
            }
            if ("status" in data && data.status != undefined) {
                this.status = data.status;
            }
            if ("progress" in data && data.progress != undefined) {
                this.progress = data.progress;
            }
            if ("speed" in data && data.speed != undefined) {
                this.speed = data.speed;
            }
        }
    }
    get file_size() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set file_size(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get status() {
        return pb_1.Message.getFieldWithDefault(this, 2, DownloadStatus.NONE) as DownloadStatus;
    }
    set status(value: DownloadStatus) {
        pb_1.Message.setField(this, 2, value);
    }
    get progress() {
        return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set progress(value: number) {
        pb_1.Message.setField(this, 3, value);
    }
    get speed() {
        return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
    }
    set speed(value: number) {
        pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
        file_size?: number;
        status?: DownloadStatus;
        progress?: number;
        speed?: number;
    }): DownloadProgress {
        const message = new DownloadProgress({});
        if (data.file_size != null) {
            message.file_size = data.file_size;
        }
        if (data.status != null) {
            message.status = data.status;
        }
        if (data.progress != null) {
            message.progress = data.progress;
        }
        if (data.speed != null) {
            message.speed = data.speed;
        }
        return message;
    }
    toObject() {
        const data: {
            file_size?: number;
            status?: DownloadStatus;
            progress?: number;
            speed?: number;
        } = {};
        if (this.file_size != null) {
            data.file_size = this.file_size;
        }
        if (this.status != null) {
            data.status = this.status;
        }
        if (this.progress != null) {
            data.progress = this.progress;
        }
        if (this.speed != null) {
            data.speed = this.speed;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.file_size != 0)
            writer.writeInt64(1, this.file_size);
        if (this.status != DownloadStatus.NONE)
            writer.writeEnum(2, this.status);
        if (this.progress != 0)
            writer.writeInt32(3, this.progress);
        if (this.speed != 0)
            writer.writeInt64(4, this.speed);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DownloadProgress {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DownloadProgress();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.file_size = reader.readInt64();
                    break;
                case 2:
                    message.status = reader.readEnum();
                    break;
                case 3:
                    message.progress = reader.readInt32();
                    break;
                case 4:
                    message.speed = reader.readInt64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): DownloadProgress {
        return DownloadProgress.deserialize(bytes);
    }
}
export class Model extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        id?: string;
        name?: string;
        url?: string;
        provider?: string;
        input_token_cost?: number;
        output_token_cost?: number;
        progress?: DownloadProgress;
        is_downloaded?: boolean;
        is_downloadable?: boolean;
        status?: DownloadStatus;
        filestore_id?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("id" in data && data.id != undefined) {
                this.id = data.id;
            }
            if ("name" in data && data.name != undefined) {
                this.name = data.name;
            }
            if ("url" in data && data.url != undefined) {
                this.url = data.url;
            }
            if ("provider" in data && data.provider != undefined) {
                this.provider = data.provider;
            }
            if ("input_token_cost" in data && data.input_token_cost != undefined) {
                this.input_token_cost = data.input_token_cost;
            }
            if ("output_token_cost" in data && data.output_token_cost != undefined) {
                this.output_token_cost = data.output_token_cost;
            }
            if ("progress" in data && data.progress != undefined) {
                this.progress = data.progress;
            }
            if ("is_downloaded" in data && data.is_downloaded != undefined) {
                this.is_downloaded = data.is_downloaded;
            }
            if ("is_downloadable" in data && data.is_downloadable != undefined) {
                this.is_downloadable = data.is_downloadable;
            }
            if ("status" in data && data.status != undefined) {
                this.status = data.status;
            }
            if ("filestore_id" in data && data.filestore_id != undefined) {
                this.filestore_id = data.filestore_id;
            }
        }
    }
    get id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get name() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set name(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get url() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set url(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    get provider() {
        return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set provider(value: string) {
        pb_1.Message.setField(this, 4, value);
    }
    get input_token_cost() {
        return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
    }
    set input_token_cost(value: number) {
        pb_1.Message.setField(this, 5, value);
    }
    get output_token_cost() {
        return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
    }
    set output_token_cost(value: number) {
        pb_1.Message.setField(this, 6, value);
    }
    get progress() {
        return pb_1.Message.getWrapperField(this, DownloadProgress, 7) as DownloadProgress;
    }
    set progress(value: DownloadProgress) {
        pb_1.Message.setWrapperField(this, 7, value);
    }
    get has_progress() {
        return pb_1.Message.getField(this, 7) != null;
    }
    get is_downloaded() {
        return pb_1.Message.getFieldWithDefault(this, 8, false) as boolean;
    }
    set is_downloaded(value: boolean) {
        pb_1.Message.setField(this, 8, value);
    }
    get is_downloadable() {
        return pb_1.Message.getFieldWithDefault(this, 9, false) as boolean;
    }
    set is_downloadable(value: boolean) {
        pb_1.Message.setField(this, 9, value);
    }
    get status() {
        return pb_1.Message.getFieldWithDefault(this, 10, DownloadStatus.NONE) as DownloadStatus;
    }
    set status(value: DownloadStatus) {
        pb_1.Message.setField(this, 10, value);
    }
    get filestore_id() {
        return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
    }
    set filestore_id(value: string) {
        pb_1.Message.setField(this, 11, value);
    }
    static fromObject(data: {
        id?: string;
        name?: string;
        url?: string;
        provider?: string;
        input_token_cost?: number;
        output_token_cost?: number;
        progress?: ReturnType<typeof DownloadProgress.prototype.toObject>;
        is_downloaded?: boolean;
        is_downloadable?: boolean;
        status?: DownloadStatus;
        filestore_id?: string;
    }): Model {
        const message = new Model({});
        if (data.id != null) {
            message.id = data.id;
        }
        if (data.name != null) {
            message.name = data.name;
        }
        if (data.url != null) {
            message.url = data.url;
        }
        if (data.provider != null) {
            message.provider = data.provider;
        }
        if (data.input_token_cost != null) {
            message.input_token_cost = data.input_token_cost;
        }
        if (data.output_token_cost != null) {
            message.output_token_cost = data.output_token_cost;
        }
        if (data.progress != null) {
            message.progress = DownloadProgress.fromObject(data.progress);
        }
        if (data.is_downloaded != null) {
            message.is_downloaded = data.is_downloaded;
        }
        if (data.is_downloadable != null) {
            message.is_downloadable = data.is_downloadable;
        }
        if (data.status != null) {
            message.status = data.status;
        }
        if (data.filestore_id != null) {
            message.filestore_id = data.filestore_id;
        }
        return message;
    }
    toObject() {
        const data: {
            id?: string;
            name?: string;
            url?: string;
            provider?: string;
            input_token_cost?: number;
            output_token_cost?: number;
            progress?: ReturnType<typeof DownloadProgress.prototype.toObject>;
            is_downloaded?: boolean;
            is_downloadable?: boolean;
            status?: DownloadStatus;
            filestore_id?: string;
        } = {};
        if (this.id != null) {
            data.id = this.id;
        }
        if (this.name != null) {
            data.name = this.name;
        }
        if (this.url != null) {
            data.url = this.url;
        }
        if (this.provider != null) {
            data.provider = this.provider;
        }
        if (this.input_token_cost != null) {
            data.input_token_cost = this.input_token_cost;
        }
        if (this.output_token_cost != null) {
            data.output_token_cost = this.output_token_cost;
        }
        if (this.progress != null) {
            data.progress = this.progress.toObject();
        }
        if (this.is_downloaded != null) {
            data.is_downloaded = this.is_downloaded;
        }
        if (this.is_downloadable != null) {
            data.is_downloadable = this.is_downloadable;
        }
        if (this.status != null) {
            data.status = this.status;
        }
        if (this.filestore_id != null) {
            data.filestore_id = this.filestore_id;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id.length)
            writer.writeString(1, this.id);
        if (this.name.length)
            writer.writeString(2, this.name);
        if (this.url.length)
            writer.writeString(3, this.url);
        if (this.provider.length)
            writer.writeString(4, this.provider);
        if (this.input_token_cost != 0)
            writer.writeDouble(5, this.input_token_cost);
        if (this.output_token_cost != 0)
            writer.writeDouble(6, this.output_token_cost);
        if (this.has_progress)
            writer.writeMessage(7, this.progress, () => this.progress.serialize(writer));
        if (this.is_downloaded != false)
            writer.writeBool(8, this.is_downloaded);
        if (this.is_downloadable != false)
            writer.writeBool(9, this.is_downloadable);
        if (this.status != DownloadStatus.NONE)
            writer.writeEnum(10, this.status);
        if (this.filestore_id.length)
            writer.writeString(11, this.filestore_id);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Model {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Model();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.id = reader.readString();
                    break;
                case 2:
                    message.name = reader.readString();
                    break;
                case 3:
                    message.url = reader.readString();
                    break;
                case 4:
                    message.provider = reader.readString();
                    break;
                case 5:
                    message.input_token_cost = reader.readDouble();
                    break;
                case 6:
                    message.output_token_cost = reader.readDouble();
                    break;
                case 7:
                    reader.readMessage(message.progress, () => message.progress = DownloadProgress.deserialize(reader));
                    break;
                case 8:
                    message.is_downloaded = reader.readBool();
                    break;
                case 9:
                    message.is_downloadable = reader.readBool();
                    break;
                case 10:
                    message.status = reader.readEnum();
                    break;
                case 11:
                    message.filestore_id = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Model {
        return Model.deserialize(bytes);
    }
}
export class DownloadModelRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        model_name?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("model_name" in data && data.model_name != undefined) {
                this.model_name = data.model_name;
            }
        }
    }
    get model_name() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set model_name(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        model_name?: string;
    }): DownloadModelRequest {
        const message = new DownloadModelRequest({});
        if (data.model_name != null) {
            message.model_name = data.model_name;
        }
        return message;
    }
    toObject() {
        const data: {
            model_name?: string;
        } = {};
        if (this.model_name != null) {
            data.model_name = this.model_name;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.model_name.length)
            writer.writeString(1, this.model_name);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DownloadModelRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DownloadModelRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.model_name = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): DownloadModelRequest {
        return DownloadModelRequest.deserialize(bytes);
    }
}
export class DownloadModelResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        message?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("message" in data && data.message != undefined) {
                this.message = data.message;
            }
        }
    }
    get message() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set message(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        message?: string;
    }): DownloadModelResponse {
        const message = new DownloadModelResponse({});
        if (data.message != null) {
            message.message = data.message;
        }
        return message;
    }
    toObject() {
        const data: {
            message?: string;
        } = {};
        if (this.message != null) {
            data.message = this.message;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.message.length)
            writer.writeString(1, this.message);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DownloadModelResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DownloadModelResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.message = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): DownloadModelResponse {
        return DownloadModelResponse.deserialize(bytes);
    }
}
export class GetLLMModelsRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {}) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") { }
    }
    static fromObject(data: {}): GetLLMModelsRequest {
        const message = new GetLLMModelsRequest({});
        return message;
    }
    toObject() {
        const data: {} = {};
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetLLMModelsRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetLLMModelsRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetLLMModelsRequest {
        return GetLLMModelsRequest.deserialize(bytes);
    }
}
export class GetLLMModelsResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        models?: Model[];
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("models" in data && data.models != undefined) {
                this.models = data.models;
            }
        }
    }
    get models() {
        return pb_1.Message.getRepeatedWrapperField(this, Model, 1) as Model[];
    }
    set models(value: Model[]) {
        pb_1.Message.setRepeatedWrapperField(this, 1, value);
    }
    static fromObject(data: {
        models?: ReturnType<typeof Model.prototype.toObject>[];
    }): GetLLMModelsResponse {
        const message = new GetLLMModelsResponse({});
        if (data.models != null) {
            message.models = data.models.map(item => Model.fromObject(item));
        }
        return message;
    }
    toObject() {
        const data: {
            models?: ReturnType<typeof Model.prototype.toObject>[];
        } = {};
        if (this.models != null) {
            data.models = this.models.map((item: Model) => item.toObject());
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.models.length)
            writer.writeRepeatedMessage(1, this.models, (item: Model) => item.serialize(writer));
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetLLMModelsResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetLLMModelsResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.models, () => pb_1.Message.addToRepeatedWrapperField(message, 1, Model.deserialize(reader), Model));
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): GetLLMModelsResponse {
        return GetLLMModelsResponse.deserialize(bytes);
    }
}
export class CancelDownloadRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        model_name?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("model_name" in data && data.model_name != undefined) {
                this.model_name = data.model_name;
            }
        }
    }
    get model_name() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set model_name(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        model_name?: string;
    }): CancelDownloadRequest {
        const message = new CancelDownloadRequest({});
        if (data.model_name != null) {
            message.model_name = data.model_name;
        }
        return message;
    }
    toObject() {
        const data: {
            model_name?: string;
        } = {};
        if (this.model_name != null) {
            data.model_name = this.model_name;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.model_name.length)
            writer.writeString(1, this.model_name);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CancelDownloadRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CancelDownloadRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.model_name = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): CancelDownloadRequest {
        return CancelDownloadRequest.deserialize(bytes);
    }
}
export class CancelDownloadResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        message?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("message" in data && data.message != undefined) {
                this.message = data.message;
            }
        }
    }
    get message() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set message(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        message?: string;
    }): CancelDownloadResponse {
        const message = new CancelDownloadResponse({});
        if (data.message != null) {
            message.message = data.message;
        }
        return message;
    }
    toObject() {
        const data: {
            message?: string;
        } = {};
        if (this.message != null) {
            data.message = this.message;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.message.length)
            writer.writeString(1, this.message);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CancelDownloadResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CancelDownloadResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.message = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): CancelDownloadResponse {
        return CancelDownloadResponse.deserialize(bytes);
    }
}
export class DeleteModelRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        model_name?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("model_name" in data && data.model_name != undefined) {
                this.model_name = data.model_name;
            }
        }
    }
    get model_name() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set model_name(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        model_name?: string;
    }): DeleteModelRequest {
        const message = new DeleteModelRequest({});
        if (data.model_name != null) {
            message.model_name = data.model_name;
        }
        return message;
    }
    toObject() {
        const data: {
            model_name?: string;
        } = {};
        if (this.model_name != null) {
            data.model_name = this.model_name;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.model_name.length)
            writer.writeString(1, this.model_name);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeleteModelRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeleteModelRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.model_name = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): DeleteModelRequest {
        return DeleteModelRequest.deserialize(bytes);
    }
}
export class DeleteModelResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        message?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("message" in data && data.message != undefined) {
                this.message = data.message;
            }
        }
    }
    get message() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set message(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        message?: string;
    }): DeleteModelResponse {
        const message = new DeleteModelResponse({});
        if (data.message != null) {
            message.message = data.message;
        }
        return message;
    }
    toObject() {
        const data: {
            message?: string;
        } = {};
        if (this.message != null) {
            data.message = this.message;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.message.length)
            writer.writeString(1, this.message);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeleteModelResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeleteModelResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.message = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): DeleteModelResponse {
        return DeleteModelResponse.deserialize(bytes);
    }
}
// Server-side service class removed for client-side compatibility
export class InferenceServiceClient {
    private _address: string;
    private _client: grpc_web_1.GrpcWebClientBase;
    constructor(address: string, credentials?: Object, options?: grpc_web_1.GrpcWebClientBaseOptions) {
        if (!options)
            options = {};
        options.format = options.format || "text";
        this._address = address;
        this._client = new grpc_web_1.GrpcWebClientBase(options);
    }
    private static Chat = new grpc_web_1.MethodDescriptor<ChatRequest, ChatResponse>("/sortedchat.inferenceservice.InferenceService/Chat", grpc_web_1.MethodType.SERVER_STREAMING, ChatRequest, ChatResponse, (message: ChatRequest) => message.serialize(), ChatResponse.deserialize);
    Chat(message: ChatRequest, metadata: grpc_web_1.Metadata | null) {
        return this._client.serverStreaming(this._address + "/sortedchat.inferenceservice.InferenceService/Chat", message, metadata || {}, InferenceServiceClient.Chat);
    }
    private static DownloadModel = new grpc_web_1.MethodDescriptor<DownloadModelRequest, DownloadModelResponse>("/sortedchat.inferenceservice.InferenceService/DownloadModel", grpc_web_1.MethodType.UNARY, DownloadModelRequest, DownloadModelResponse, (message: DownloadModelRequest) => message.serialize(), DownloadModelResponse.deserialize);
    DownloadModel(message: DownloadModelRequest, metadata: grpc_web_1.Metadata | null) {
        return this._client.thenableCall<DownloadModelRequest, DownloadModelResponse>(this._address + "/sortedchat.inferenceservice.InferenceService/DownloadModel", message, metadata || {}, InferenceServiceClient.DownloadModel);
    }
    private static GetLLMModels = new grpc_web_1.MethodDescriptor<GetLLMModelsRequest, GetLLMModelsResponse>("/sortedchat.inferenceservice.InferenceService/GetLLMModels", grpc_web_1.MethodType.SERVER_STREAMING, GetLLMModelsRequest, GetLLMModelsResponse, (message: GetLLMModelsRequest) => message.serialize(), GetLLMModelsResponse.deserialize);
    GetLLMModels(message: GetLLMModelsRequest, metadata: grpc_web_1.Metadata | null) {
        return this._client.serverStreaming(this._address + "/sortedchat.inferenceservice.InferenceService/GetLLMModels", message, metadata || {}, InferenceServiceClient.GetLLMModels);
    }
    private static CancelDownload = new grpc_web_1.MethodDescriptor<CancelDownloadRequest, CancelDownloadResponse>("/sortedchat.inferenceservice.InferenceService/CancelDownload", grpc_web_1.MethodType.UNARY, CancelDownloadRequest, CancelDownloadResponse, (message: CancelDownloadRequest) => message.serialize(), CancelDownloadResponse.deserialize);
    CancelDownload(message: CancelDownloadRequest, metadata: grpc_web_1.Metadata | null) {
        return this._client.thenableCall<CancelDownloadRequest, CancelDownloadResponse>(this._address + "/sortedchat.inferenceservice.InferenceService/CancelDownload", message, metadata || {}, InferenceServiceClient.CancelDownload);
    }
    private static DeleteModel = new grpc_web_1.MethodDescriptor<DeleteModelRequest, DeleteModelResponse>("/sortedchat.inferenceservice.InferenceService/DeleteModel", grpc_web_1.MethodType.UNARY, DeleteModelRequest, DeleteModelResponse, (message: DeleteModelRequest) => message.serialize(), DeleteModelResponse.deserialize);
    DeleteModel(message: DeleteModelRequest, metadata: grpc_web_1.Metadata | null) {
        return this._client.thenableCall<DeleteModelRequest, DeleteModelResponse>(this._address + "/sortedchat.inferenceservice.InferenceService/DeleteModel", message, metadata || {}, InferenceServiceClient.DeleteModel);
    }
}
