// @ts-nocheck
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.29.2
 * source: realtimeservice.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "grpc-web";
import * as grpc_web_1 from "grpc-web";
export class OfferRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        offer?: string;
        model?: string;
        provider?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("offer" in data && data.offer != undefined) {
                this.offer = data.offer;
            }
            if ("model" in data && data.model != undefined) {
                this.model = data.model;
            }
            if ("provider" in data && data.provider != undefined) {
                this.provider = data.provider;
            }
        }
    }
    get offer() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set offer(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    get model() {
        return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set model(value: string) {
        pb_1.Message.setField(this, 2, value);
    }
    get provider() {
        return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
    }
    set provider(value: string) {
        pb_1.Message.setField(this, 3, value);
    }
    static fromObject(data: {
        offer?: string;
        model?: string;
        provider?: string;
    }): OfferRequest {
        const message = new OfferRequest({});
        if (data.offer != null) {
            message.offer = data.offer;
        }
        if (data.model != null) {
            message.model = data.model;
        }
        if (data.provider != null) {
            message.provider = data.provider;
        }
        return message;
    }
    toObject() {
        const data: {
            offer?: string;
            model?: string;
            provider?: string;
        } = {};
        if (this.offer != null) {
            data.offer = this.offer;
        }
        if (this.model != null) {
            data.model = this.model;
        }
        if (this.provider != null) {
            data.provider = this.provider;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.offer.length)
            writer.writeString(1, this.offer);
        if (this.model.length)
            writer.writeString(2, this.model);
        if (this.provider.length)
            writer.writeString(3, this.provider);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): OfferRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new OfferRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.offer = reader.readString();
                    break;
                case 2:
                    message.model = reader.readString();
                    break;
                case 3:
                    message.provider = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): OfferRequest {
        return OfferRequest.deserialize(bytes);
    }
}
export class OfferResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        offer?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("offer" in data && data.offer != undefined) {
                this.offer = data.offer;
            }
        }
    }
    get offer() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set offer(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        offer?: string;
    }): OfferResponse {
        const message = new OfferResponse({});
        if (data.offer != null) {
            message.offer = data.offer;
        }
        return message;
    }
    toObject() {
        const data: {
            offer?: string;
        } = {};
        if (this.offer != null) {
            data.offer = this.offer;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.offer.length)
            writer.writeString(1, this.offer);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): OfferResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new OfferResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.offer = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): OfferResponse {
        return OfferResponse.deserialize(bytes);
    }
}
export class IceCandidateRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        candidate?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("candidate" in data && data.candidate != undefined) {
                this.candidate = data.candidate;
            }
        }
    }
    get candidate() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set candidate(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        candidate?: string;
    }): IceCandidateRequest {
        const message = new IceCandidateRequest({});
        if (data.candidate != null) {
            message.candidate = data.candidate;
        }
        return message;
    }
    toObject() {
        const data: {
            candidate?: string;
        } = {};
        if (this.candidate != null) {
            data.candidate = this.candidate;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.candidate.length)
            writer.writeString(1, this.candidate);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): IceCandidateRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new IceCandidateRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.candidate = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): IceCandidateRequest {
        return IceCandidateRequest.deserialize(bytes);
    }
}
export class IceCandidateResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        message?: string;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("message" in data && data.message != undefined) {
                this.message = data.message;
            }
        }
    }
    get message() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set message(value: string) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        message?: string;
    }): IceCandidateResponse {
        const message = new IceCandidateResponse({});
        if (data.message != null) {
            message.message = data.message;
        }
        return message;
    }
    toObject() {
        const data: {
            message?: string;
        } = {};
        if (this.message != null) {
            data.message = this.message;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.message.length)
            writer.writeString(1, this.message);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): IceCandidateResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new IceCandidateResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.message = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): IceCandidateResponse {
        return IceCandidateResponse.deserialize(bytes);
    }
}
// Server-side service class removed for client-side compatibility
export class RealtimeServiceClient {
    private _address: string;
    private _client: grpc_web_1.GrpcWebClientBase;
    constructor(address: string, credentials?: Object, options?: grpc_web_1.GrpcWebClientBaseOptions) {
        if (!options)
            options = {};
        options.format = options.format || "text";
        this._address = address;
        this._client = new grpc_web_1.GrpcWebClientBase(options);
    }
    private static Offer = new grpc_web_1.MethodDescriptor<OfferRequest, OfferResponse>("/sortedchat.RealtimeService/Offer", grpc_web_1.MethodType.UNARY, OfferRequest, OfferResponse, (message: OfferRequest) => message.serialize(), OfferResponse.deserialize);
    Offer(message: OfferRequest, metadata: grpc_web_1.Metadata | null) {
        return this._client.thenableCall<OfferRequest, OfferResponse>(this._address + "/sortedchat.RealtimeService/Offer", message, metadata || {}, RealtimeServiceClient.Offer);
    }
    private static IceCandidate = new grpc_web_1.MethodDescriptor<IceCandidateRequest, IceCandidateResponse>("/sortedchat.RealtimeService/IceCandidate", grpc_web_1.MethodType.UNARY, IceCandidateRequest, IceCandidateResponse, (message: IceCandidateRequest) => message.serialize(), IceCandidateResponse.deserialize);
    IceCandidate(message: IceCandidateRequest, metadata: grpc_web_1.Metadata | null) {
        return this._client.thenableCall<IceCandidateRequest, IceCandidateResponse>(this._address + "/sortedchat.RealtimeService/IceCandidate", message, metadata || {}, RealtimeServiceClient.IceCandidate);
    }
}
