// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: chatservice.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SortedChat_Chat_FullMethodName                        = "/sortedchat.SortedChat/Chat"
	SortedChat_GenerateChatName_FullMethodName            = "/sortedchat.SortedChat/GenerateChatName"
	SortedChat_GetHistory_FullMethodName                  = "/sortedchat.SortedChat/GetHistory"
	SortedChat_GetChatList_FullMethodName                 = "/sortedchat.SortedChat/GetChatList"
	SortedChat_CreateChat_FullMethodName                  = "/sortedchat.SortedChat/CreateChat"
	SortedChat_SearchChat_FullMethodName                  = "/sortedchat.SortedChat/SearchChat"
	SortedChat_ListModel_FullMethodName                   = "/sortedchat.SortedChat/ListModel"
	SortedChat_GetRAGDocumentReference_FullMethodName     = "/sortedchat.SortedChat/GetRAGDocumentReference"
	SortedChat_DeleteDocument_FullMethodName              = "/sortedchat.SortedChat/DeleteDocument"
	SortedChat_CreateProject_FullMethodName               = "/sortedchat.SortedChat/CreateProject"
	SortedChat_GetProjects_FullMethodName                 = "/sortedchat.SortedChat/GetProjects"
	SortedChat_ListDocuments_FullMethodName               = "/sortedchat.SortedChat/ListDocuments"
	SortedChat_SubmitGenerateEmbeddingsJob_FullMethodName = "/sortedchat.SortedChat/SubmitGenerateEmbeddingsJob"
	SortedChat_BranchAChat_FullMethodName                 = "/sortedchat.SortedChat/BranchAChat"
	SortedChat_ListChatBranch_FullMethodName              = "/sortedchat.SortedChat/ListChatBranch"
	SortedChat_DeleteChat_FullMethodName                  = "/sortedchat.SortedChat/DeleteChat"
	SortedChat_RestoreChat_FullMethodName                 = "/sortedchat.SortedChat/RestoreChat"
	SortedChat_RenameItem_FullMethodName                  = "/sortedchat.SortedChat/RenameItem"
	SortedChat_AddModel_FullMethodName                    = "/sortedchat.SortedChat/AddModel"
)

// SortedChatClient is the client API for SortedChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SortedChatClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error)
	GenerateChatName(ctx context.Context, in *GenerateChatNameRequest, opts ...grpc.CallOption) (*GenerateChatNameResponse, error)
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	GetChatList(ctx context.Context, in *GetChatListRequest, opts ...grpc.CallOption) (*GetChatListResponse, error)
	CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*CreateChatResponse, error)
	SearchChat(ctx context.Context, in *ChatSearchRequest, opts ...grpc.CallOption) (*ChatSearchResponse, error)
	ListModel(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	GetRAGDocumentReference(ctx context.Context, in *RAGDocumentReferenceRequest, opts ...grpc.CallOption) (*RAGDocumentReferenceResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	SubmitGenerateEmbeddingsJob(ctx context.Context, in *GenerateEmbeddingRequest, opts ...grpc.CallOption) (*GenerateEmbeddingResponse, error)
	BranchAChat(ctx context.Context, in *BranchAChatRequest, opts ...grpc.CallOption) (*BranchAChatResponse, error)
	ListChatBranch(ctx context.Context, in *ListChatBranchRequest, opts ...grpc.CallOption) (*ListChatBranchResponse, error)
	DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*DeleteChatResponse, error)
	RestoreChat(ctx context.Context, in *RestoreChatRequest, opts ...grpc.CallOption) (*RestoreChatResponse, error)
	RenameItem(ctx context.Context, in *RenameItemRequest, opts ...grpc.CallOption) (*RenameItemResponse, error)
	AddModel(ctx context.Context, in *AddModelRequest, opts ...grpc.CallOption) (*AddModelResponse, error)
}

type sortedChatClient struct {
	cc grpc.ClientConnInterface
}

func NewSortedChatClient(cc grpc.ClientConnInterface) SortedChatClient {
	return &sortedChatClient{cc}
}

func (c *sortedChatClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SortedChat_ServiceDesc.Streams[0], SortedChat_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SortedChat_ChatClient = grpc.ServerStreamingClient[ChatResponse]

func (c *sortedChatClient) GenerateChatName(ctx context.Context, in *GenerateChatNameRequest, opts ...grpc.CallOption) (*GenerateChatNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateChatNameResponse)
	err := c.cc.Invoke(ctx, SortedChat_GenerateChatName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, SortedChat_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) GetChatList(ctx context.Context, in *GetChatListRequest, opts ...grpc.CallOption) (*GetChatListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatListResponse)
	err := c.cc.Invoke(ctx, SortedChat_GetChatList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*CreateChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChatResponse)
	err := c.cc.Invoke(ctx, SortedChat_CreateChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) SearchChat(ctx context.Context, in *ChatSearchRequest, opts ...grpc.CallOption) (*ChatSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatSearchResponse)
	err := c.cc.Invoke(ctx, SortedChat_SearchChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) ListModel(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, SortedChat_ListModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) GetRAGDocumentReference(ctx context.Context, in *RAGDocumentReferenceRequest, opts ...grpc.CallOption) (*RAGDocumentReferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAGDocumentReferenceResponse)
	err := c.cc.Invoke(ctx, SortedChat_GetRAGDocumentReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, SortedChat_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, SortedChat_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, SortedChat_GetProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, SortedChat_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) SubmitGenerateEmbeddingsJob(ctx context.Context, in *GenerateEmbeddingRequest, opts ...grpc.CallOption) (*GenerateEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateEmbeddingResponse)
	err := c.cc.Invoke(ctx, SortedChat_SubmitGenerateEmbeddingsJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) BranchAChat(ctx context.Context, in *BranchAChatRequest, opts ...grpc.CallOption) (*BranchAChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BranchAChatResponse)
	err := c.cc.Invoke(ctx, SortedChat_BranchAChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) ListChatBranch(ctx context.Context, in *ListChatBranchRequest, opts ...grpc.CallOption) (*ListChatBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatBranchResponse)
	err := c.cc.Invoke(ctx, SortedChat_ListChatBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*DeleteChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChatResponse)
	err := c.cc.Invoke(ctx, SortedChat_DeleteChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) RestoreChat(ctx context.Context, in *RestoreChatRequest, opts ...grpc.CallOption) (*RestoreChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreChatResponse)
	err := c.cc.Invoke(ctx, SortedChat_RestoreChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) RenameItem(ctx context.Context, in *RenameItemRequest, opts ...grpc.CallOption) (*RenameItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameItemResponse)
	err := c.cc.Invoke(ctx, SortedChat_RenameItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortedChatClient) AddModel(ctx context.Context, in *AddModelRequest, opts ...grpc.CallOption) (*AddModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddModelResponse)
	err := c.cc.Invoke(ctx, SortedChat_AddModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SortedChatServer is the server API for SortedChat service.
// All implementations must embed UnimplementedSortedChatServer
// for forward compatibility.
type SortedChatServer interface {
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error
	GenerateChatName(context.Context, *GenerateChatNameRequest) (*GenerateChatNameResponse, error)
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	GetChatList(context.Context, *GetChatListRequest) (*GetChatListResponse, error)
	CreateChat(context.Context, *CreateChatRequest) (*CreateChatResponse, error)
	SearchChat(context.Context, *ChatSearchRequest) (*ChatSearchResponse, error)
	ListModel(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	GetRAGDocumentReference(context.Context, *RAGDocumentReferenceRequest) (*RAGDocumentReferenceResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error)
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	SubmitGenerateEmbeddingsJob(context.Context, *GenerateEmbeddingRequest) (*GenerateEmbeddingResponse, error)
	BranchAChat(context.Context, *BranchAChatRequest) (*BranchAChatResponse, error)
	ListChatBranch(context.Context, *ListChatBranchRequest) (*ListChatBranchResponse, error)
	DeleteChat(context.Context, *DeleteChatRequest) (*DeleteChatResponse, error)
	RestoreChat(context.Context, *RestoreChatRequest) (*RestoreChatResponse, error)
	RenameItem(context.Context, *RenameItemRequest) (*RenameItemResponse, error)
	AddModel(context.Context, *AddModelRequest) (*AddModelResponse, error)
	mustEmbedUnimplementedSortedChatServer()
}

// UnimplementedSortedChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSortedChatServer struct{}

func (UnimplementedSortedChatServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedSortedChatServer) GenerateChatName(context.Context, *GenerateChatNameRequest) (*GenerateChatNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateChatName not implemented")
}
func (UnimplementedSortedChatServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedSortedChatServer) GetChatList(context.Context, *GetChatListRequest) (*GetChatListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatList not implemented")
}
func (UnimplementedSortedChatServer) CreateChat(context.Context, *CreateChatRequest) (*CreateChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChat not implemented")
}
func (UnimplementedSortedChatServer) SearchChat(context.Context, *ChatSearchRequest) (*ChatSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchChat not implemented")
}
func (UnimplementedSortedChatServer) ListModel(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModel not implemented")
}
func (UnimplementedSortedChatServer) GetRAGDocumentReference(context.Context, *RAGDocumentReferenceRequest) (*RAGDocumentReferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRAGDocumentReference not implemented")
}
func (UnimplementedSortedChatServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedSortedChatServer) CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedSortedChatServer) GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjects not implemented")
}
func (UnimplementedSortedChatServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedSortedChatServer) SubmitGenerateEmbeddingsJob(context.Context, *GenerateEmbeddingRequest) (*GenerateEmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitGenerateEmbeddingsJob not implemented")
}
func (UnimplementedSortedChatServer) BranchAChat(context.Context, *BranchAChatRequest) (*BranchAChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BranchAChat not implemented")
}
func (UnimplementedSortedChatServer) ListChatBranch(context.Context, *ListChatBranchRequest) (*ListChatBranchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChatBranch not implemented")
}
func (UnimplementedSortedChatServer) DeleteChat(context.Context, *DeleteChatRequest) (*DeleteChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChat not implemented")
}
func (UnimplementedSortedChatServer) RestoreChat(context.Context, *RestoreChatRequest) (*RestoreChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreChat not implemented")
}
func (UnimplementedSortedChatServer) RenameItem(context.Context, *RenameItemRequest) (*RenameItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameItem not implemented")
}
func (UnimplementedSortedChatServer) AddModel(context.Context, *AddModelRequest) (*AddModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddModel not implemented")
}
func (UnimplementedSortedChatServer) mustEmbedUnimplementedSortedChatServer() {}
func (UnimplementedSortedChatServer) testEmbeddedByValue()                    {}

// UnsafeSortedChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SortedChatServer will
// result in compilation errors.
type UnsafeSortedChatServer interface {
	mustEmbedUnimplementedSortedChatServer()
}

func RegisterSortedChatServer(s grpc.ServiceRegistrar, srv SortedChatServer) {
	// If the following call pancis, it indicates UnimplementedSortedChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SortedChat_ServiceDesc, srv)
}

func _SortedChat_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SortedChatServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SortedChat_ChatServer = grpc.ServerStreamingServer[ChatResponse]

func _SortedChat_GenerateChatName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateChatNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).GenerateChatName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_GenerateChatName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).GenerateChatName(ctx, req.(*GenerateChatNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_GetChatList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).GetChatList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_GetChatList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).GetChatList(ctx, req.(*GetChatListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_CreateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).CreateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_CreateChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).CreateChat(ctx, req.(*CreateChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_SearchChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).SearchChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_SearchChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).SearchChat(ctx, req.(*ChatSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_ListModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).ListModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_ListModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).ListModel(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_GetRAGDocumentReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGDocumentReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).GetRAGDocumentReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_GetRAGDocumentReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).GetRAGDocumentReference(ctx, req.(*RAGDocumentReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_GetProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_SubmitGenerateEmbeddingsJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).SubmitGenerateEmbeddingsJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_SubmitGenerateEmbeddingsJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).SubmitGenerateEmbeddingsJob(ctx, req.(*GenerateEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_BranchAChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BranchAChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).BranchAChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_BranchAChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).BranchAChat(ctx, req.(*BranchAChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_ListChatBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).ListChatBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_ListChatBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).ListChatBranch(ctx, req.(*ListChatBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_DeleteChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).DeleteChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_DeleteChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).DeleteChat(ctx, req.(*DeleteChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_RestoreChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).RestoreChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_RestoreChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).RestoreChat(ctx, req.(*RestoreChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_RenameItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).RenameItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_RenameItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).RenameItem(ctx, req.(*RenameItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortedChat_AddModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortedChatServer).AddModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortedChat_AddModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortedChatServer).AddModel(ctx, req.(*AddModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SortedChat_ServiceDesc is the grpc.ServiceDesc for SortedChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SortedChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sortedchat.SortedChat",
	HandlerType: (*SortedChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateChatName",
			Handler:    _SortedChat_GenerateChatName_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _SortedChat_GetHistory_Handler,
		},
		{
			MethodName: "GetChatList",
			Handler:    _SortedChat_GetChatList_Handler,
		},
		{
			MethodName: "CreateChat",
			Handler:    _SortedChat_CreateChat_Handler,
		},
		{
			MethodName: "SearchChat",
			Handler:    _SortedChat_SearchChat_Handler,
		},
		{
			MethodName: "ListModel",
			Handler:    _SortedChat_ListModel_Handler,
		},
		{
			MethodName: "GetRAGDocumentReference",
			Handler:    _SortedChat_GetRAGDocumentReference_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _SortedChat_DeleteDocument_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _SortedChat_CreateProject_Handler,
		},
		{
			MethodName: "GetProjects",
			Handler:    _SortedChat_GetProjects_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _SortedChat_ListDocuments_Handler,
		},
		{
			MethodName: "SubmitGenerateEmbeddingsJob",
			Handler:    _SortedChat_SubmitGenerateEmbeddingsJob_Handler,
		},
		{
			MethodName: "BranchAChat",
			Handler:    _SortedChat_BranchAChat_Handler,
		},
		{
			MethodName: "ListChatBranch",
			Handler:    _SortedChat_ListChatBranch_Handler,
		},
		{
			MethodName: "DeleteChat",
			Handler:    _SortedChat_DeleteChat_Handler,
		},
		{
			MethodName: "RestoreChat",
			Handler:    _SortedChat_RestoreChat_Handler,
		},
		{
			MethodName: "RenameItem",
			Handler:    _SortedChat_RenameItem_Handler,
		},
		{
			MethodName: "AddModel",
			Handler:    _SortedChat_AddModel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _SortedChat_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chatservice.proto",
}

const (
	SettingService_GetSetting_FullMethodName             = "/sortedchat.SettingService/GetSetting"
	SettingService_SetSetting_FullMethodName             = "/sortedchat.SettingService/SetSetting"
	SettingService_GetProviderSetting_FullMethodName     = "/sortedchat.SettingService/GetProviderSetting"
	SettingService_SetProviderSetting_FullMethodName     = "/sortedchat.SettingService/SetProviderSetting"
	SettingService_GetAllProviderSettings_FullMethodName = "/sortedchat.SettingService/GetAllProviderSettings"
	SettingService_SetAllProviderSettings_FullMethodName = "/sortedchat.SettingService/SetAllProviderSettings"
	SettingService_IsFirstBoot_FullMethodName            = "/sortedchat.SettingService/IsFirstBoot"
	SettingService_TestConnection_FullMethodName         = "/sortedchat.SettingService/TestConnection"
)

// SettingServiceClient is the client API for SettingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettingServiceClient interface {
	GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*GetSettingResponse, error)
	SetSetting(ctx context.Context, in *SetSettingRequest, opts ...grpc.CallOption) (*SetSettingResponse, error)
	GetProviderSetting(ctx context.Context, in *GetProviderSettingRequest, opts ...grpc.CallOption) (*GetProviderSettingResponse, error)
	SetProviderSetting(ctx context.Context, in *SetProviderSettingRequest, opts ...grpc.CallOption) (*SetProviderSettingResponse, error)
	GetAllProviderSettings(ctx context.Context, in *GetAllProviderSettingsRequest, opts ...grpc.CallOption) (*GetAllProviderSettingsResponse, error)
	SetAllProviderSettings(ctx context.Context, in *SetAllProviderSettingsRequest, opts ...grpc.CallOption) (*SetAllProviderSettingsResponse, error)
	IsFirstBoot(ctx context.Context, in *IsFirstBootRequest, opts ...grpc.CallOption) (*IsFirstBootResponse, error)
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
}

type settingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingServiceClient(cc grpc.ClientConnInterface) SettingServiceClient {
	return &settingServiceClient{cc}
}

func (c *settingServiceClient) GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*GetSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSettingResponse)
	err := c.cc.Invoke(ctx, SettingService_GetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) SetSetting(ctx context.Context, in *SetSettingRequest, opts ...grpc.CallOption) (*SetSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSettingResponse)
	err := c.cc.Invoke(ctx, SettingService_SetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) GetProviderSetting(ctx context.Context, in *GetProviderSettingRequest, opts ...grpc.CallOption) (*GetProviderSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderSettingResponse)
	err := c.cc.Invoke(ctx, SettingService_GetProviderSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) SetProviderSetting(ctx context.Context, in *SetProviderSettingRequest, opts ...grpc.CallOption) (*SetProviderSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetProviderSettingResponse)
	err := c.cc.Invoke(ctx, SettingService_SetProviderSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) GetAllProviderSettings(ctx context.Context, in *GetAllProviderSettingsRequest, opts ...grpc.CallOption) (*GetAllProviderSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllProviderSettingsResponse)
	err := c.cc.Invoke(ctx, SettingService_GetAllProviderSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) SetAllProviderSettings(ctx context.Context, in *SetAllProviderSettingsRequest, opts ...grpc.CallOption) (*SetAllProviderSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAllProviderSettingsResponse)
	err := c.cc.Invoke(ctx, SettingService_SetAllProviderSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) IsFirstBoot(ctx context.Context, in *IsFirstBootRequest, opts ...grpc.CallOption) (*IsFirstBootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFirstBootResponse)
	err := c.cc.Invoke(ctx, SettingService_IsFirstBoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, SettingService_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingServiceServer is the server API for SettingService service.
// All implementations must embed UnimplementedSettingServiceServer
// for forward compatibility.
type SettingServiceServer interface {
	GetSetting(context.Context, *GetSettingRequest) (*GetSettingResponse, error)
	SetSetting(context.Context, *SetSettingRequest) (*SetSettingResponse, error)
	GetProviderSetting(context.Context, *GetProviderSettingRequest) (*GetProviderSettingResponse, error)
	SetProviderSetting(context.Context, *SetProviderSettingRequest) (*SetProviderSettingResponse, error)
	GetAllProviderSettings(context.Context, *GetAllProviderSettingsRequest) (*GetAllProviderSettingsResponse, error)
	SetAllProviderSettings(context.Context, *SetAllProviderSettingsRequest) (*SetAllProviderSettingsResponse, error)
	IsFirstBoot(context.Context, *IsFirstBootRequest) (*IsFirstBootResponse, error)
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error)
	mustEmbedUnimplementedSettingServiceServer()
}

// UnimplementedSettingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettingServiceServer struct{}

func (UnimplementedSettingServiceServer) GetSetting(context.Context, *GetSettingRequest) (*GetSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSetting not implemented")
}
func (UnimplementedSettingServiceServer) SetSetting(context.Context, *SetSettingRequest) (*SetSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSetting not implemented")
}
func (UnimplementedSettingServiceServer) GetProviderSetting(context.Context, *GetProviderSettingRequest) (*GetProviderSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderSetting not implemented")
}
func (UnimplementedSettingServiceServer) SetProviderSetting(context.Context, *SetProviderSettingRequest) (*SetProviderSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProviderSetting not implemented")
}
func (UnimplementedSettingServiceServer) GetAllProviderSettings(context.Context, *GetAllProviderSettingsRequest) (*GetAllProviderSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllProviderSettings not implemented")
}
func (UnimplementedSettingServiceServer) SetAllProviderSettings(context.Context, *SetAllProviderSettingsRequest) (*SetAllProviderSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAllProviderSettings not implemented")
}
func (UnimplementedSettingServiceServer) IsFirstBoot(context.Context, *IsFirstBootRequest) (*IsFirstBootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsFirstBoot not implemented")
}
func (UnimplementedSettingServiceServer) TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedSettingServiceServer) mustEmbedUnimplementedSettingServiceServer() {}
func (UnimplementedSettingServiceServer) testEmbeddedByValue()                        {}

// UnsafeSettingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingServiceServer will
// result in compilation errors.
type UnsafeSettingServiceServer interface {
	mustEmbedUnimplementedSettingServiceServer()
}

func RegisterSettingServiceServer(s grpc.ServiceRegistrar, srv SettingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSettingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettingService_ServiceDesc, srv)
}

func _SettingService_GetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).GetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_GetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).GetSetting(ctx, req.(*GetSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_SetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).SetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_SetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).SetSetting(ctx, req.(*SetSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_GetProviderSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).GetProviderSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_GetProviderSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).GetProviderSetting(ctx, req.(*GetProviderSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_SetProviderSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProviderSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).SetProviderSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_SetProviderSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).SetProviderSetting(ctx, req.(*SetProviderSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_GetAllProviderSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProviderSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).GetAllProviderSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_GetAllProviderSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).GetAllProviderSettings(ctx, req.(*GetAllProviderSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_SetAllProviderSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAllProviderSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).SetAllProviderSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_SetAllProviderSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).SetAllProviderSettings(ctx, req.(*SetAllProviderSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_IsFirstBoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFirstBootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).IsFirstBoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_IsFirstBoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).IsFirstBoot(ctx, req.(*IsFirstBootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingService_ServiceDesc is the grpc.ServiceDesc for SettingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sortedchat.SettingService",
	HandlerType: (*SettingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSetting",
			Handler:    _SettingService_GetSetting_Handler,
		},
		{
			MethodName: "SetSetting",
			Handler:    _SettingService_SetSetting_Handler,
		},
		{
			MethodName: "GetProviderSetting",
			Handler:    _SettingService_GetProviderSetting_Handler,
		},
		{
			MethodName: "SetProviderSetting",
			Handler:    _SettingService_SetProviderSetting_Handler,
		},
		{
			MethodName: "GetAllProviderSettings",
			Handler:    _SettingService_GetAllProviderSettings_Handler,
		},
		{
			MethodName: "SetAllProviderSettings",
			Handler:    _SettingService_SetAllProviderSettings_Handler,
		},
		{
			MethodName: "IsFirstBoot",
			Handler:    _SettingService_IsFirstBoot_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _SettingService_TestConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatservice.proto",
}

const (
	AgentService_CreateAgent_FullMethodName      = "/sortedchat.AgentService/CreateAgent"
	AgentService_UpdateAgent_FullMethodName      = "/sortedchat.AgentService/UpdateAgent"
	AgentService_GetAgents_FullMethodName        = "/sortedchat.AgentService/GetAgents"
	AgentService_CreateSession_FullMethodName    = "/sortedchat.AgentService/CreateSession"
	AgentService_GetSession_FullMethodName       = "/sortedchat.AgentService/GetSession"
	AgentService_GetSessions_FullMethodName      = "/sortedchat.AgentService/GetSessions"
	AgentService_AgentChat_FullMethodName        = "/sortedchat.AgentService/AgentChat"
	AgentService_GetAgentMessages_FullMethodName = "/sortedchat.AgentService/GetAgentMessages"
	AgentService_GetAgentMessage_FullMethodName  = "/sortedchat.AgentService/GetAgentMessage"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ------- Agent Service -------
type AgentServiceClient interface {
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error)
	UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*UpdateAgentResponse, error)
	// rpc GetAgent(GetAgentRequest) returns (GetAgentResponse);
	GetAgents(ctx context.Context, in *GetAgentsRequest, opts ...grpc.CallOption) (*GetAgentsResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error)
	// doesnot sound right, its more like chat with agent to continue with last session
	AgentChat(ctx context.Context, in *AgentChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentChatResponse], error)
	// we may need to edit history of a session ? or delete a message ?
	// TODO: thinking
	GetAgentMessages(ctx context.Context, in *GetAgentMessagesRequest, opts ...grpc.CallOption) (*GetAgentMessagesResponse, error)
	// rpc DeleteMessage(DeleteMessageRequest) returns (DeleteMessageResponse);
	// rpc GetMessage(GetMessageRequest) returns (GetMessageResponse);
	GetAgentMessage(ctx context.Context, in *GetAgentMessageRequest, opts ...grpc.CallOption) (*GetAgentMessageResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*UpdateAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_UpdateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgents(ctx context.Context, in *GetAgentsRequest, opts ...grpc.CallOption) (*GetAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, AgentService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, AgentService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*GetSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AgentChat(ctx context.Context, in *AgentChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_AgentChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentChatRequest, AgentChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_AgentChatClient = grpc.ServerStreamingClient[AgentChatResponse]

func (c *agentServiceClient) GetAgentMessages(ctx context.Context, in *GetAgentMessagesRequest, opts ...grpc.CallOption) (*GetAgentMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentMessagesResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAgentMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgentMessage(ctx context.Context, in *GetAgentMessageRequest, opts ...grpc.CallOption) (*GetAgentMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentMessageResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAgentMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// ------- Agent Service -------
type AgentServiceServer interface {
	CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error)
	UpdateAgent(context.Context, *UpdateAgentRequest) (*UpdateAgentResponse, error)
	// rpc GetAgent(GetAgentRequest) returns (GetAgentResponse);
	GetAgents(context.Context, *GetAgentsRequest) (*GetAgentsResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	GetSessions(context.Context, *GetSessionsRequest) (*GetSessionsResponse, error)
	// doesnot sound right, its more like chat with agent to continue with last session
	AgentChat(*AgentChatRequest, grpc.ServerStreamingServer[AgentChatResponse]) error
	// we may need to edit history of a session ? or delete a message ?
	// TODO: thinking
	GetAgentMessages(context.Context, *GetAgentMessagesRequest) (*GetAgentMessagesResponse, error)
	// rpc DeleteMessage(DeleteMessageRequest) returns (DeleteMessageResponse);
	// rpc GetMessage(GetMessageRequest) returns (GetMessageResponse);
	GetAgentMessage(context.Context, *GetAgentMessageRequest) (*GetAgentMessageResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedAgentServiceServer) UpdateAgent(context.Context, *UpdateAgentRequest) (*UpdateAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedAgentServiceServer) GetAgents(context.Context, *GetAgentsRequest) (*GetAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgents not implemented")
}
func (UnimplementedAgentServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAgentServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedAgentServiceServer) GetSessions(context.Context, *GetSessionsRequest) (*GetSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessions not implemented")
}
func (UnimplementedAgentServiceServer) AgentChat(*AgentChatRequest, grpc.ServerStreamingServer[AgentChatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method AgentChat not implemented")
}
func (UnimplementedAgentServiceServer) GetAgentMessages(context.Context, *GetAgentMessagesRequest) (*GetAgentMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentMessages not implemented")
}
func (UnimplementedAgentServiceServer) GetAgentMessage(context.Context, *GetAgentMessageRequest) (*GetAgentMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentMessage not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateAgent(ctx, req.(*UpdateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgents(ctx, req.(*GetAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSessions(ctx, req.(*GetSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AgentChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AgentChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).AgentChat(m, &grpc.GenericServerStream[AgentChatRequest, AgentChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_AgentChatServer = grpc.ServerStreamingServer[AgentChatResponse]

func _AgentService_GetAgentMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgentMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgentMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgentMessages(ctx, req.(*GetAgentMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgentMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgentMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgentMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgentMessage(ctx, req.(*GetAgentMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sortedchat.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _AgentService_CreateAgent_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _AgentService_UpdateAgent_Handler,
		},
		{
			MethodName: "GetAgents",
			Handler:    _AgentService_GetAgents_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _AgentService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _AgentService_GetSession_Handler,
		},
		{
			MethodName: "GetSessions",
			Handler:    _AgentService_GetSessions_Handler,
		},
		{
			MethodName: "GetAgentMessages",
			Handler:    _AgentService_GetAgentMessages_Handler,
		},
		{
			MethodName: "GetAgentMessage",
			Handler:    _AgentService_GetAgentMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentChat",
			Handler:       _AgentService_AgentChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chatservice.proto",
}
