general_settings:
  master_key: your-secure-key
  litellm_proxy_url: http://localhost:4000
model_list:
  - model_name: openai/gpt-4.1
    litellm_params:
      api_key: ${OPENAI_API_KEY}
      api_base: ${OPENAI_URL}
      model: gpt-4.1
