version: '3.8'
services:
  dev:
    image: ghcr.io/sortedstartup/docker-images/dev-go-npm-grpc:may-15-2025-1
    volumes:
      - ../..:/workspaces:cached
    # ports:
    #   - "3000:3000"
    environment:
      - POSTGRES_DATABASE=devdb
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=database
      - DB_TYPE=postgres
    command: sleep infinity
    depends_on:
      - database

  database:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DATABASE: devdb
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: