syntax = "proto3";

package sortedchat;

option go_package = "sortedstartup/chatservice/proto";


service SortedChat {
    rpc Chat(ChatRequest) returns (stream ChatResponse);
    rpc GenerateChatName(GenerateChatNameRequest) returns (GenerateChatNameResponse);
    rpc GetHistory(GetHistoryRequest) returns (GetHistoryResponse);
    rpc GetChatList(GetChatListRequest) returns (GetChatListResponse);
    rpc CreateChat(CreateChatRequest) returns (CreateChatResponse);
    rpc ListModel(ListModelsRequest) returns (ListModelsResponse);
    rpc SearchChat(ChatSearchRequest) returns (ChatSearchResponse);

    rpc GetRAGDocumentReference (RAGDocumentReferenceRequest) returns (RAGDocumentReferenceResponse);
    rpc DeleteDocument(DeleteDocumentRequest) returns (DeleteDocumentResponse);

    rpc CreateProject(CreateProjectRequest) returns (CreateProjectResponse);
    rpc GetProjects(GetProjectsRequest) returns (GetProjectsResponse);
    rpc ListDocuments(ListDocumentsRequest) returns(ListDocumentsResponse);
    rpc SubmitGenerateEmbeddingsJob(GenerateEmbeddingRequest) returns (GenerateEmbeddingResponse);

    rpc BranchAChat(BranchAChatRequest) returns (BranchAChatResponse);
    rpc ListChatBranch(ListChatBranchRequest) returns (ListChatBranchResponse);
    rpc DeleteChat(DeleteChatRequest) returns (DeleteChatResponse);
    rpc RestoreChat(RestoreChatRequest) returns (RestoreChatResponse);
    rpc RenameChat(RenameChatRequest) returns (RenameChatResponse);
}

message RenameChatRequest {
  string chat_id = 1;
  string name = 2;
}
message RenameChatResponse {
  string message = 1;
}

message RestoreChatRequest {
  string chat_id = 1;
}
message RestoreChatResponse {
  string message = 1;
}

message DeleteChatRequest {
  string chat_id = 1;
  Operation operation = 2;
  enum Operation {
    DELETE = 0;
    SOFT_DELETE = 1;
  } 
}
message DeleteChatResponse {
  string message = 1;
}

message DeleteDocumentRequest {
  string project_id = 1;
  string doc_id = 2;
}

message DeleteDocumentResponse {
  string message = 1;
}

message RAGDocumentReferenceRequest{
  string message_id = 1;
  string project_id = 2;
  string docId = 3;  
}

message RAGDocumentReferenceResponse {
  RAGDocumentReference reference = 1;
}

service SettingService {
    rpc GetSetting(GetSettingRequest) returns (GetSettingResponse);
    rpc SetSetting(SetSettingRequest) returns (SetSettingResponse);
}

message Settings {
   string OPENAI_API_KEY = 1;
   string OPENAI_API_URL = 2;
   string OLLAMA_URL = 3;
}

message GetSettingRequest {}

message GetSettingResponse {
    Settings settings = 1;
}

message SetSettingRequest {
    Settings settings = 1;
}

message SetSettingResponse {
    string message = 1;
}


message CreateChatRequest {
  string name = 1;
  string project_id = 2;
}

message CreateChatResponse {
  string message = 1;
  string chat_id = 2;
}

message ProjectContext {
  string project_id = 1;
  bool rag_enabled = 2;
}

message ChatRequest {
    string text = 1;
    string chatId = 2;
    string model = 3;
    ProjectContext project_context = 4;
}

message ChatResponse {
  oneof response {
    string text = 1;
    // was introduced to send assistant message id, because it is generated server side
    // sending one of the multiple oneof's help us do all of this in one streaming API call
    MessageSummary summary = 2;
    RAGDocumentReferenceSummaryList document_reference = 3; 
  }
}

// TODO: reasonable limits from server side, limit to 10 (constant in server side) docs
message RAGDocumentReferenceSummaryList {
  repeated Summary summary = 1;
  message Summary {
    string doc_id = 1;
    string file_name = 2;
    int32 chunkCount = 3;
  }
}

message RAGDocumentReference {
  string doc_id = 1;
  string file_name = 2;
  repeated Chunk Chunks  = 3;
  message Chunk  {
    string chunk_text = 3;
    int32 start_byte = 4;
    int32 end_byte = 5;
    float simillarity = 6; 
  }
}

message ResponseSummary {
  string message_id = 1;
}

message GetHistoryRequest {
  string chatId = 1;
}

message GetHistoryResponse {
  repeated ChatMessage history = 1;
  ChatInfo chat_metadata = 2;
}

message ChatMessage {
  string role = 1;
  string content = 2;
  string message_id = 3;
  repeated RAGDocumentReference references = 4;
  bool rag_enabled = 5;
  string model = 6;
  int32 input_tokens = 7;
  int32 output_tokens = 8;
  int32 cached_tokens = 9;
  float cost = 10;
}

message GetChatListRequest {
  string project_id = 1;
  bool soft_deleted = 2; 
  //later we create a filter object because we might have to add more filters
}

message GetChatListResponse {
  repeated ChatInfo chats = 1;
}

//total chat cost/token
message ChatInfo {
  string chatId = 1;
  string name = 2;
  float cost = 3;
  int32 input_token_count = 4;
  int32 output_token_count = 5;
  int32 cached_token_count = 6;
}

message ModelListInfo {
  string id = 1;
  string label = 2;
  string provider = 3;
  string url = 4;
  float input_token_cost = 5;
  float output_token_cost = 6;
}

message ListModelsRequest {}

message ListModelsResponse {
  repeated ModelListInfo models = 1;
}

message ChatSearchRequest {
  string query = 1;
}

message SearchResult {
  string chat_name = 1;
  string chat_id = 2;
  string matched_text = 3;
}

message ChatSearchResponse {
  string query = 1;
  repeated SearchResult results = 2;
}

message CreateProjectRequest {
  string name = 1;
  string description = 2;
  string additional_data = 3; 
}

message CreateProjectResponse {
  string message = 1;
  string project_id = 2;
}

message GetProjectsRequest {}

message GetProjectsResponse {
  repeated Project projects = 1;
}

message Project {
  string id = 1;
  string name = 2;
  string description = 3;
  string additional_data = 4;
  string created_at = 5;
  string updated_at = 6;
}

message ListDocumentsRequest {
  string project_id = 1;
}

message ListDocumentsResponse {
  repeated Document documents = 1;
}

message Document {
  int64 id = 1;
  string project_id = 2;
  string docs_id = 3;
  string file_name = 4;
  string created_at = 5;
  string updated_at = 6;
  Embedding_Status embedding_status=7;
}

enum Embedding_Status {
  STATUS_QUEUED = 0;
  STATUS_IN_PROGRESS = 1;
  STATUS_ERROR = 2;
  STATUS_SUCCESS = 3;
}

message GenerateEmbeddingRequest {
  string project_id = 1;
}

message GenerateEmbeddingResponse {
  string message = 1;
}

message GenerateChatNameRequest{
  string chat_id = 1;
  string message = 2; //first message in new chat
  string model = 3;
}

message GenerateChatNameResponse {
  string chat_name = 1;
}

message BranchAChatRequest {
  string source_chat_id = 1;           // Chat to branch from
  string branch_from_message_id = 2;    // Message ID where branch starts
  string branch_name = 3;               // Optional name for new branch
}


message BranchAChatResponse {
  string message = 1;                   // Success/error message
  string new_chat_id = 2;              // ID of newly created branch
}

message ListChatBranchRequest {
  string chat_id = 1;
}

message ListChatBranchResponse {
  repeated ChatInfo branch_chat_list = 1;
}