syntax = "proto3";

package sortedchat;

option go_package = "sortedstartup/inferenceservice/proto";

service InferenceService {
  rpc DownloadModel(DownloadModelRequest) returns (DownloadModelResponse);
  rpc ListModels(ListModelsRequest) returns (stream ListModelsResponse);
}

message Model {
  string id = 1;
  string name = 2;
  string url = 3;
  string provider = 4;
  double input_token_cost = 5;
  double output_token_cost = 6;
  string progress = 7;
  bool is_downloaded = 8;
  bool is_downloadable = 9;
  int32 status = 10;
}
  
message DownloadModelRequest {
  string model_name = 1;
}

message DownloadModelResponse {
  string message = 1;
}

message ListModelsRequest {
}

message ListModelsResponse {
  repeated Model models = 1;
}