// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: realtimeservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         string                 `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferRequest) Reset() {
	*x = OfferRequest{}
	mi := &file_realtimeservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferRequest) ProtoMessage() {}

func (x *OfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtimeservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferRequest.ProtoReflect.Descriptor instead.
func (*OfferRequest) Descriptor() ([]byte, []int) {
	return file_realtimeservice_proto_rawDescGZIP(), []int{0}
}

func (x *OfferRequest) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

func (x *OfferRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type OfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         string                 `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferResponse) Reset() {
	*x = OfferResponse{}
	mi := &file_realtimeservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferResponse) ProtoMessage() {}

func (x *OfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realtimeservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferResponse.ProtoReflect.Descriptor instead.
func (*OfferResponse) Descriptor() ([]byte, []int) {
	return file_realtimeservice_proto_rawDescGZIP(), []int{1}
}

func (x *OfferResponse) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

var File_realtimeservice_proto protoreflect.FileDescriptor

const file_realtimeservice_proto_rawDesc = "" +
	"\n" +
	"\x15realtimeservice.proto\x12\n" +
	"sortedchat\":\n" +
	"\fOfferRequest\x12\x14\n" +
	"\x05offer\x18\x01 \x01(\tR\x05offer\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"%\n" +
	"\rOfferResponse\x12\x14\n" +
	"\x05offer\x18\x01 \x01(\tR\x05offer2O\n" +
	"\x0fRealtimeService\x12<\n" +
	"\x05Offer\x12\x18.sortedchat.OfferRequest\x1a\x19.sortedchat.OfferResponseB%Z#sortedstartup/realtimeservice/protob\x06proto3"

var (
	file_realtimeservice_proto_rawDescOnce sync.Once
	file_realtimeservice_proto_rawDescData []byte
)

func file_realtimeservice_proto_rawDescGZIP() []byte {
	file_realtimeservice_proto_rawDescOnce.Do(func() {
		file_realtimeservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtimeservice_proto_rawDesc), len(file_realtimeservice_proto_rawDesc)))
	})
	return file_realtimeservice_proto_rawDescData
}

var file_realtimeservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_realtimeservice_proto_goTypes = []any{
	(*OfferRequest)(nil),  // 0: sortedchat.OfferRequest
	(*OfferResponse)(nil), // 1: sortedchat.OfferResponse
}
var file_realtimeservice_proto_depIdxs = []int32{
	0, // 0: sortedchat.RealtimeService.Offer:input_type -> sortedchat.OfferRequest
	1, // 1: sortedchat.RealtimeService.Offer:output_type -> sortedchat.OfferResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_realtimeservice_proto_init() }
func file_realtimeservice_proto_init() {
	if File_realtimeservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtimeservice_proto_rawDesc), len(file_realtimeservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realtimeservice_proto_goTypes,
		DependencyIndexes: file_realtimeservice_proto_depIdxs,
		MessageInfos:      file_realtimeservice_proto_msgTypes,
	}.Build()
	File_realtimeservice_proto = out.File
	file_realtimeservice_proto_goTypes = nil
	file_realtimeservice_proto_depIdxs = nil
}
